import html as html_module
import ipaddress
import re
import secrets
import sys
from pathlib import Path
from typing import Annotated

import tomlkit
import typer
from typer_examples import example

from frappe_manager import CLI_BENCHES_DIRECTORY
from frappe_manager.commands import check_bench_migration_required
from frappe_manager.output_manager import get_global_output_handler
from frappe_manager.utils.callbacks import sitename_callback, sites_autocompletion_callback

# Maintenance owns a marked BLOCK inside vhost.d/<domain>, not the whole file:
# other fm features (upload limits) and hand-written directives share the same
# jwilder per-domain file and must survive enable/disable untouched.
_BLOCK_BEGIN_PREFIX = "# fm:maintenance BEGIN"
_BLOCK_END = "# fm:maintenance END"
_BLOCK_RE = re.compile(r"^# fm:maintenance BEGIN.*?^# fm:maintenance END\n?", re.DOTALL | re.MULTILINE)


def _has_fm_block(text: str) -> bool:
    return _BLOCK_BEGIN_PREFIX in text


def _strip_fm_block(text: str) -> str:
    return _BLOCK_RE.sub("", text)


# Conventioned per-bench custom page: drop this file into the bench's configs
# directory once and every future enable uses it automatically.
_BENCH_PAGE_RELPATH = ("configs", "maintenance.html")

_DEFAULT_MESSAGE = "Scheduled maintenance is in progress. We will be back shortly."

_ALLOW_PATH_RE = re.compile(r"^/[A-Za-z0-9/_.~%-]*\*?$")

_PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Down for maintenance</title>
<style>
  body {{ margin: 0; min-height: 100vh; display: flex; align-items: center; justify-content: center;
         font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #f4f5f6; color: #1f272e; }}
  main {{ text-align: center; padding: 2rem; }}
  h1 {{ font-size: 1.6rem; margin: 0 0 .6rem; }}
  p {{ color: #505a62; margin: 0; }}
</style>
</head>
<body>
<main>
  <h1>Down for maintenance</h1>
  <p>{message}</p>
</main>
</body>
</html>
"""


def _page_filename(bench_name: str) -> str:
    return f"fm-maintenance-{bench_name}.html"


def _vhost_conf(
    bench_name: str,
    token: str,
    html_container_dir: str,
    code: int,
    retry_after: int,
    allow_ips: list[str],
    allow_paths: list[str],
    secure_cookie: bool,
) -> str:
    """Per-domain nginx-proxy vhost.d conf: everyone gets the maintenance page
    with the configured status code; the bypass cookie (or its exact set-URL),
    allow-listed IPs, and allow-listed paths pass through to the bench. /api/*
    requests receive a JSON body instead of the HTML page."""
    allow_lines = []
    for ip in allow_ips:
        allow_lines.append(f'if ($remote_addr = "{ip}") {{\n    set $fm_maintenance 0;\n}}')
    for path in allow_paths:
        if path.endswith("*"):
            allow_lines.append(f'if ($uri ~ "^{re.escape(path[:-1])}") {{\n    set $fm_maintenance 0;\n}}')
        else:
            allow_lines.append(f"if ($uri = {path}) {{\n    set $fm_maintenance 0;\n}}")
    allow_block = ("\n".join(allow_lines) + "\n") if allow_lines else ""

    retry_after_line = f"    add_header Retry-After {retry_after} always;\n" if retry_after > 0 else ""
    secure = "; Secure" if secure_cookie else ""

    return f"""{_BLOCK_BEGIN_PREFIX} (bench: {bench_name}) generated by `fm maintenance`; do not edit this block
set $fm_maintenance 1;
if ($cookie_fm_maintenance_bypass = "{token}") {{
    set $fm_maintenance 0;
}}
if ($uri = /fm-bypass/{token}) {{
    set $fm_maintenance 0;
}}
if ($uri = /fm-bypass/off) {{
    set $fm_maintenance 0;
}}
if ($uri = /fm-maintenance-page) {{
    set $fm_maintenance 0;
}}
{allow_block}if ($uri ~ ^/api/) {{
    set $fm_maintenance "${{fm_maintenance}}-api";
}}
if ($fm_maintenance = "1-api") {{
    rewrite ^ /fm-maintenance-json last;
}}
if ($fm_maintenance = 1) {{
    return {code};
}}
error_page {code} /fm-maintenance-page;
location = /fm-maintenance-page {{
    internal;
    root {html_container_dir};
{retry_after_line}    try_files /{_page_filename(bench_name)} =502;
}}
location = /fm-maintenance-json {{
    default_type application/json;
{retry_after_line}    return {code} '{{"message":"Service temporarily unavailable for maintenance"}}';
}}
location = /fm-bypass/{token} {{
    add_header Set-Cookie "fm_maintenance_bypass={token}; Path=/; Max-Age=86400; HttpOnly{secure}";
    return 302 /;
}}
location = /fm-bypass/off {{
    add_header Set-Cookie "fm_maintenance_bypass=; Path=/; Max-Age=0{secure}";
    return 302 /;
}}
{_BLOCK_END}
"""


def _bench_domains(benchname: str) -> tuple[list[str], dict[str, bool]]:
    """(primary + alias domains, per-domain TLS state) read straight from
    bench_config.toml, so maintenance works even when the bench itself is stopped
    or broken.

    Certificates are per domain: every ``[[ssl.certificates]]`` entry carries its
    own ``ssl_type``, so a bench can serve its primary domain over TLS and an alias
    over plain http. A top-level ``ssl.ssl_type`` would always read as absent,
    because export_to_toml never writes that key.
    """
    config_path = CLI_BENCHES_DIRECTORY / benchname / "bench_config.toml"
    data = tomlkit.parse(config_path.read_text())
    domains = [benchname, *list(data.get("alias_domains", []) or [])]
    certificates = (data.get("ssl") or {}).get("certificates") or []
    secured = {str(cert.get("domain")) for cert in certificates if str(cert.get("ssl_type", "none")) != "none"}
    return domains, {domain: domain in secured for domain in domains}


def _extract_token(conf_text: str) -> str | None:
    match = re.search(r'\$cookie_fm_maintenance_bypass = "([A-Za-z0-9]+)"', conf_text)
    return match.group(1) if match else None


def _extract_code(conf_text: str) -> int:
    match = re.search(r"\$fm_maintenance = 1\) \{\s*return (\d+);", conf_text)
    return int(match.group(1)) if match else 503


def _extract_bench(conf_text: str) -> str:
    match = re.search(r"\(bench: ([^)]+)\)", conf_text)
    return match.group(1) if match else "?"


def _resolve_page_html(benchname: str, page: Path | None, message: str | None) -> str:
    """Custom page resolution, first match wins: --page file, --message into
    the built-in template, the bench's conventioned maintenance.html, then the
    built-in default."""
    if page is not None:
        return page.read_text()
    if message is not None:
        return _PAGE_TEMPLATE.format(message=html_module.escape(message))
    bench_page = CLI_BENCHES_DIRECTORY.joinpath(benchname, *_BENCH_PAGE_RELPATH)
    if bench_page.exists():
        return bench_page.read_text()
    return _PAGE_TEMPLATE.format(message=_DEFAULT_MESSAGE)


def _maintenance_sitename_callback(sitename: str | None):
    """Allow `fm maintenance --status` without a bench (lists every domain in
    maintenance); every other invocation gets the standard prompt/validation."""
    if sitename is None and "--status" in sys.argv:
        return None
    return sitename_callback(sitename)


@example(
    "Put a bench into maintenance",
    "{benchname}",
    detail="Serves a maintenance page for every domain of the bench (aliases included) at the global nginx proxy, and prints a secret bypass URL that lets you keep using the real site while everyone else sees the page.",
    benchname="mybench",
)
@example(
    "Maintenance with team and webhook exceptions",
    "{benchname} --allow-ip 203.0.113.7 --allow-path '/api/method/payment_webhook*' --retry-after 1800",
    detail="The office IP and the payment webhook keep reaching the real bench while everyone else sees the page with a Retry-After of 30 minutes.",
    benchname="mybench",
)
@example(
    "Custom page or message",
    "{benchname} --message 'Upgrading the database, back at 17:00 UTC'",
    detail="Injects the text into fm's maintenance page. Use --page FILE for fully custom HTML, or drop a configs/maintenance.html into the bench directory to make it the permanent default for this bench.",
    benchname="mybench",
)
@example(
    "Maintenance with a different status code",
    "{benchname} --response-code 404",
    detail="Serves the maintenance page with HTTP 404 instead of 503, e.g. to make the site look absent instead of temporarily down.",
    benchname="mybench",
)
@example(
    "Show maintenance state",
    "{benchname} --status",
    detail="Shows whether maintenance is active per domain and reprints the bypass URL. Omit the bench name to list every domain currently in maintenance.",
    benchname="mybench",
)
@example(
    "Bring the bench back",
    "{benchname} --off",
    detail="Removes the maintenance page from every domain; visitors reach the bench again immediately.",
    benchname="mybench",
)
def maintenance(
    ctx: typer.Context,
    benchname: Annotated[
        str | None,
        typer.Argument(
            help="Name of the bench. Optional with --status (lists every domain in maintenance).",
            autocompletion=sites_autocompletion_callback,
            callback=_maintenance_sitename_callback,
        ),
    ] = None,
    off: Annotated[
        bool,
        typer.Option("--off", help="Disable maintenance mode and serve the bench again."),
    ] = False,
    status: Annotated[
        bool,
        typer.Option("--status", help="Show maintenance state per domain without changing anything."),
    ] = False,
    response_code: Annotated[
        int,
        typer.Option(
            "--response-code",
            help="HTTP status code served while maintenance is on (400-599). Default 503 Service Unavailable.",
        ),
    ] = 503,
    retry_after: Annotated[
        int,
        typer.Option(
            "--retry-after",
            help="Retry-After header value in seconds on maintenance responses (tells crawlers the outage is temporary). 0 disables the header.",
        ),
    ] = 300,
    allow_ip: Annotated[
        list[str],
        typer.Option(
            "--allow-ip",
            help="Client IP that bypasses maintenance (repeatable). Exact IPs only; behind a CDN or external proxy this matches the forwarding IP unless real-IP forwarding is configured.",
            show_default=False,
        ),
    ] = [],
    allow_path: Annotated[
        list[str],
        typer.Option(
            "--allow-path",
            help="Request path that bypasses maintenance, e.g. payment webhooks or health checks (repeatable). Exact match; append * for a prefix match.",
            show_default=False,
        ),
    ] = [],
    message: Annotated[
        str | None,
        typer.Option(
            "--message",
            help="Custom text shown on fm's built-in maintenance page.",
            show_default=False,
        ),
    ] = None,
    page: Annotated[
        Path | None,
        typer.Option(
            "--page",
            help="Fully custom maintenance page: path to an HTML file served as-is. Tip: a configs/maintenance.html in the bench directory is picked up automatically on every enable.",
            show_default=False,
        ),
    ] = None,
    rotate_token: Annotated[
        bool,
        typer.Option(
            "--rotate-token",
            help="Generate a fresh bypass token, invalidating every previously issued bypass cookie/URL.",
        ),
    ] = False,
):
    """
    Toggle a proxy-level maintenance page for a bench (all domains, aliases included).

    Maintenance is enforced at the global nginx proxy, so it holds even while the bench itself is stopped, restarting, or being deployed. Everyone gets the maintenance page (503 by default; tune with --response-code) and /api/* clients get a JSON body; opening the printed secret bypass URL sets a cookie that lets YOU through to the real site (open /fm-bypass/off to drop it). Allow-listed IPs and paths (webhooks, health checks) pass through as well.

    Re-running enable replaces the previous settings (code, allow lists, page); the bypass token is kept unless --rotate-token is given. The page comes from --page, --message, the bench's configs/maintenance.html, or fm's default, in that order.
    """

    output = get_global_output_handler()

    # Same gate every other command that MUTATES a live bench carries (update, restart, start,
    # auth, reset...). Maintenance rewrites the bench's vhost in the shared proxy, so running it
    # against a bench whose on-disk layout predates the current fm is how you get a half-migrated
    # vhost. `stop` and `delete` are deliberately exempt: you must always be able to stop or remove
    # a bench you cannot migrate.
    check_bench_migration_required(benchname)

    services = ctx.obj["services"]
    vhostd_dir = Path(services.proxy_storage.dirs.vhostd.host)
    html_mount = services.proxy_storage.dirs.html
    html_host_dir = Path(html_mount.host)
    html_container_dir = str(html_mount.container)

    if benchname is None:
        # Only reachable via `fm maintenance --status` (see callback): list
        # every domain currently in maintenance across all benches.
        found = 0
        if vhostd_dir.exists():
            for conf in sorted(vhostd_dir.iterdir()):
                if not conf.is_file():
                    continue
                text = conf.read_text()
                if not _has_fm_block(text):
                    continue
                found += 1
                output.print(
                    f"{conf.name}: maintenance ON (bench {_extract_bench(text)}, code {_extract_code(text)}, "
                    f"bypass token {_extract_token(text)})"
                )
        if not found:
            output.print("No domain is in maintenance")
        return

    if off and status:
        output.error("--off cannot be combined with --status", exception=typer.Exit(code=1))

    if not 400 <= response_code <= 599:
        output.error(
            f"--response-code must be an HTTP error status between 400 and 599, got {response_code}",
            exception=typer.Exit(code=1),
        )

    if message is not None and page is not None:
        output.error("--message cannot be combined with --page (pick one)", exception=typer.Exit(code=1))

    if page is not None and not page.exists():
        output.error(f"--page file not found: {page}", exception=typer.Exit(code=1))

    for ip in allow_ip:
        try:
            ipaddress.ip_address(ip)
        except ValueError:
            output.error(
                f"--allow-ip must be a single IPv4/IPv6 address, got {ip!r} (CIDR ranges are not supported here)",
                exception=typer.Exit(code=1),
            )

    for path in allow_path:
        if not _ALLOW_PATH_RE.match(path):
            output.error(
                f"--allow-path must be an absolute path like /api/method/ping (optionally ending in *), got {path!r}",
                exception=typer.Exit(code=1),
            )

    domains, domain_ssl = _bench_domains(benchname)

    def scheme_for(domain: str) -> str:
        return "https" if domain_ssl.get(domain) else "http"

    def conf_path(domain: str) -> Path:
        return vhostd_dir / domain

    def active(path: Path) -> bool:
        return path.exists() and _has_fm_block(path.read_text())

    if status:
        for domain in domains:
            path = conf_path(domain)
            if active(path):
                text = path.read_text()
                output.print(
                    f"{domain}: maintenance ON "
                    f"(code {_extract_code(text)}, bypass: {scheme_for(domain)}://{domain}/fm-bypass/{_extract_token(text)})"
                )
            elif path.exists():
                output.print(f"{domain}: custom vhost config present (no fm maintenance block)")
            else:
                output.print(f"{domain}: maintenance off")
        return

    if off:

        def disable(path: Path) -> None:
            # Remove ONLY the fm block; other directives in the shared
            # per-domain file (e.g. upload limits) must survive.
            remainder = _strip_fm_block(path.read_text()).strip("\n")
            if remainder:
                path.write_text(remainder + "\n")
            else:
                path.unlink()

        removed = 0
        for domain in domains:
            path = conf_path(domain)
            if not active(path):
                continue
            disable(path)
            removed += 1

        # A domain dropped from the bench (`fm update B --remove-alias x`) keeps its vhost.d
        # file, and the loop above only knows the CURRENT bench_config.toml -- so its
        # maintenance block would stay live: still listed by --status, and inherited (page and
        # bypass token) by whichever bench claims that domain next. Sweep those orphans, which
        # the block itself names as ours.
        orphans: list[str] = []
        if vhostd_dir.exists():
            for conf in sorted(vhostd_dir.iterdir()):
                if conf.name in domains or not conf.is_file():
                    continue
                text = conf.read_text()
                if not _has_fm_block(text) or _extract_bench(text) != benchname:
                    continue
                disable(conf)
                orphans.append(conf.name)
        removed += len(orphans)

        if not removed:
            output.print("Maintenance was not enabled")
            return
        services.nginx_controller.reload()
        output.print(f"Maintenance disabled for: {', '.join([*domains, *orphans])}")
        return

    # Enable. Reuse the existing token when re-running (idempotent) unless a
    # rotation was requested.
    token = None
    for domain in domains:
        path = conf_path(domain)
        if active(path) and token is None:
            token = _extract_token(path.read_text())
    if rotate_token or token is None:
        token = secrets.token_hex(16)

    html_host_dir.mkdir(parents=True, exist_ok=True)
    (html_host_dir / _page_filename(benchname)).write_text(_resolve_page_html(benchname, page, message))
    vhostd_dir.mkdir(parents=True, exist_ok=True)
    for domain in domains:
        path = conf_path(domain)
        # The Secure flag on the bypass cookie is decided per domain: an alias
        # served over plain http must not be handed a cookie the browser will
        # only ever send back over TLS.
        block = _vhost_conf(
            benchname,
            token,
            html_container_dir,
            response_code,
            retry_after,
            allow_ip,
            allow_path,
            domain_ssl[domain],
        )
        # Prepend our block, preserving whatever else shares the file
        # (upload limits, hand-written directives).
        remainder = _strip_fm_block(path.read_text()).strip("\n") if path.exists() else ""
        path.write_text(block + (remainder + "\n" if remainder else ""))

    services.nginx_controller.reload()

    output.print(f"Maintenance enabled for: {', '.join(domains)} (serving {response_code})")
    if allow_ip:
        output.print(f"Allowed IPs: {', '.join(allow_ip)}")
    if allow_path:
        output.print(f"Allowed paths: {', '.join(allow_path)}")
    output.print(
        f"Bypass (sets a cookie so you see the real site): {scheme_for(domains[0])}://{domains[0]}/fm-bypass/{token}"
    )
    output.print(f"Drop the bypass again: {scheme_for(domains[0])}://{domains[0]}/fm-bypass/off")
