import secrets
from pathlib import Path
from typing import Annotated

import tomlkit
import typer
from typer_examples import example

from frappe_manager import CLI_BENCHES_DIRECTORY
from frappe_manager.output_manager import get_global_output_handler
from frappe_manager.utils.callbacks import sitename_callback, sites_autocompletion_callback

# First line of every conf this command writes; enable/disable refuse to touch
# vhost files that do not carry it (a hand-authored vhost.d file must survive).
_MARKER = "# fm:maintenance"

_PAGE_FILENAME = "fm-maintenance.html"

_PAGE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Down for maintenance</title>
<style>
  body { margin: 0; min-height: 100vh; display: flex; align-items: center; justify-content: center;
         font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #f4f5f6; color: #1f272e; }
  main { text-align: center; padding: 2rem; }
  h1 { font-size: 1.6rem; margin: 0 0 .6rem; }
  p { color: #505a62; margin: 0; }
</style>
</head>
<body>
<main>
  <h1>Down for maintenance</h1>
  <p>Scheduled maintenance is in progress. We will be back shortly.</p>
</main>
</body>
</html>
"""


def _vhost_conf(bench_name: str, token: str, html_container_dir: str, code: int) -> str:
    """Per-domain nginx-proxy vhost.d conf: everyone gets the maintenance page
    with the configured status code; requests carrying the bypass cookie (or
    hitting the exact bypass URL that sets it) pass through to the bench."""
    return f"""{_MARKER} generated by `fm maintenance` (bench: {bench_name}); do not edit
set $fm_maintenance 1;
if ($cookie_fm_maintenance_bypass = "{token}") {{
    set $fm_maintenance 0;
}}
if ($uri = /fm-bypass/{token}) {{
    set $fm_maintenance 0;
}}
if ($uri = /fm-bypass/off) {{
    set $fm_maintenance 0;
}}
if ($uri = /fm-maintenance-page) {{
    set $fm_maintenance 0;
}}
if ($fm_maintenance = 1) {{
    return {code};
}}
error_page {code} /fm-maintenance-page;
location = /fm-maintenance-page {{
    internal;
    root {html_container_dir};
    try_files /{_PAGE_FILENAME} =502;
}}
location = /fm-bypass/{token} {{
    add_header Set-Cookie "fm_maintenance_bypass={token}; Path=/; Max-Age=86400; HttpOnly";
    return 302 /;
}}
location = /fm-bypass/off {{
    add_header Set-Cookie "fm_maintenance_bypass=; Path=/; Max-Age=0";
    return 302 /;
}}
"""


def _bench_domains(benchname: str) -> tuple[list[str], bool]:
    """(primary + alias domains, has_ssl) read straight from bench_config.toml,
    so maintenance works even when the bench itself is stopped or broken."""
    config_path = CLI_BENCHES_DIRECTORY / benchname / "bench_config.toml"
    data = tomlkit.parse(config_path.read_text())
    domains = [benchname, *list(data.get("alias_domains", []) or [])]
    ssl = data.get("ssl") or {}
    has_ssl = bool(ssl) and str(ssl.get("ssl_type", "none")) != "none"
    return domains, has_ssl


def _extract_token(conf_text: str) -> str | None:
    import re

    match = re.search(r'\$cookie_fm_maintenance_bypass = "([A-Za-z0-9]+)"', conf_text)
    return match.group(1) if match else None


def _extract_code(conf_text: str) -> int:
    import re

    match = re.search(r"\$fm_maintenance = 1\) \{\s*return (\d+);", conf_text)
    return int(match.group(1)) if match else 503


@example(
    "Put a bench into maintenance",
    "{benchname}",
    detail="Serves a maintenance page for every domain of the bench (aliases included) at the global nginx proxy, and prints a secret bypass URL that lets you keep using the real site while everyone else sees the page.",
    benchname="mybench",
)
@example(
    "Show maintenance state",
    "{benchname} --status",
    detail="Shows whether maintenance is active per domain and reprints the bypass URL.",
    benchname="mybench",
)
@example(
    "Bring the bench back",
    "{benchname} --off",
    detail="Removes the maintenance page from every domain; visitors reach the bench again immediately.",
    benchname="mybench",
)
@example(
    "Maintenance with a different status code",
    "{benchname} --response-code 404",
    detail="Serves the maintenance page with HTTP 404 instead of 503, e.g. to make the site look absent instead of temporarily down.",
    benchname="mybench",
)
def maintenance(
    ctx: typer.Context,
    benchname: Annotated[
        str | None,
        typer.Argument(
            help="Name of the bench.",
            autocompletion=sites_autocompletion_callback,
            callback=sitename_callback,
        ),
    ] = None,
    off: Annotated[
        bool,
        typer.Option("--off", help="Disable maintenance mode and serve the bench again."),
    ] = False,
    status: Annotated[
        bool,
        typer.Option("--status", help="Show maintenance state per domain without changing anything."),
    ] = False,
    response_code: Annotated[
        int,
        typer.Option(
            "--response-code",
            help="HTTP status code served while maintenance is on (400-599). Default 503 Service Unavailable.",
        ),
    ] = 503,
):
    """
    Toggle a proxy-level maintenance page for a bench (all domains, aliases included).

    Maintenance is enforced at the global nginx proxy, so it holds even while the bench itself is stopped, restarting, or being deployed. Everyone gets the maintenance page (503 by default; tune with --response-code); opening the printed secret bypass URL sets a cookie that lets YOU through to the real site (open /fm-bypass/off to drop it).
    """

    output = get_global_output_handler()

    if benchname is None:  # sitename_callback prompts or raises before this.
        raise typer.Exit(1)

    if off and status:
        output.error("--off cannot be combined with --status", exception=typer.Exit(code=1))

    if not 400 <= response_code <= 599:
        output.error(
            f"--response-code must be an HTTP error status between 400 and 599, got {response_code}",
            exception=typer.Exit(code=1),
        )

    services = ctx.obj["services"]
    vhostd_dir = Path(services.proxy_storage.dirs.vhostd.host)
    html_mount = services.proxy_storage.dirs.html
    html_host_dir = Path(html_mount.host)
    html_container_dir = str(html_mount.container)

    domains, has_ssl = _bench_domains(benchname)
    scheme = "https" if has_ssl else "http"

    def conf_path(domain: str) -> Path:
        return vhostd_dir / domain

    def owned(path: Path) -> bool:
        return path.exists() and path.read_text().startswith(_MARKER)

    def foreign(path: Path) -> bool:
        return path.exists() and not path.read_text().startswith(_MARKER)

    if status:
        for domain in domains:
            path = conf_path(domain)
            if owned(path):
                token = _extract_token(path.read_text())
                output.print(
                    f"{domain}: maintenance ON "
                    f"(code {_extract_code(path.read_text())}, bypass: {scheme}://{domain}/fm-bypass/{token})"
                )
            elif foreign(path):
                output.print(f"{domain}: custom vhost config present (not fm maintenance)")
            else:
                output.print(f"{domain}: maintenance off")
        return

    if off:
        removed = 0
        for domain in domains:
            path = conf_path(domain)
            if owned(path):
                path.unlink()
                removed += 1
            elif foreign(path):
                output.warning(f"{domain}: vhost config not written by fm maintenance; leaving it untouched")
        if not removed:
            output.print("Maintenance was not enabled")
            return
        services.nginx_controller.reload()
        output.print(f"Maintenance disabled for: {', '.join(domains)}")
        return

    # Enable. Reuse the existing token when re-running (idempotent).
    token = None
    for domain in domains:
        path = conf_path(domain)
        if foreign(path):
            output.error(
                f"A custom vhost config already exists for {domain} ({path}); "
                "refusing to overwrite it with the maintenance page.",
                exception=typer.Exit(code=1),
            )
        if owned(path) and token is None:
            token = _extract_token(path.read_text())
    if token is None:
        token = secrets.token_hex(16)

    html_host_dir.mkdir(parents=True, exist_ok=True)
    (html_host_dir / _PAGE_FILENAME).write_text(_PAGE_HTML)
    vhostd_dir.mkdir(parents=True, exist_ok=True)
    for domain in domains:
        conf_path(domain).write_text(_vhost_conf(benchname, token, html_container_dir, response_code))

    services.nginx_controller.reload()

    output.print(f"Maintenance enabled for: {', '.join(domains)} (serving {response_code})")
    output.print(f"Bypass (sets a cookie so you see the real site): {scheme}://{domains[0]}/fm-bypass/{token}")
    output.print(f"Drop the bypass again: {scheme}://{domains[0]}/fm-bypass/off")
