"""
Manages symlinks between certificate files and nginx-proxy directories.

This module handles the creation and removal of symbolic links that connect
Let's Encrypt certificates (stored in ssl/ directory) to the nginx-proxy certs/
directory where nginx-proxy expects to find them.
"""

from pathlib import Path

from frappe_manager.ssl_manager.storage_config import SSLStorageConfig
from frappe_manager.utils.helpers import create_symlink


class CertificateLinkManager:
    """
    Manages certificate symlinks for nginx-proxy.

    This class is responsible for creating and removing symbolic links between:
    - Certificate files generated by Let's Encrypt (in ssl/ directory)
    - Certificate locations expected by nginx-proxy (in certs/ directory)

    The symlinks allow nginx-proxy to access certificates for both primary
    and alias domains without duplicating certificate files.

    Attributes:
        storage_config: Configuration for SSL storage paths
    """

    def __init__(self, storage_config: SSLStorageConfig):
        """
        Initialize the certificate link manager.

        Args:
            storage_config: Configuration object with paths to ssl and certs directories

        Raises:
            ValueError: If storage_config paths are invalid
        """
        self.storage_config = storage_config
        # Validate that required directories exist
        self._validate_prerequisites()

    def _validate_prerequisites(self):
        """
        Validate that prerequisite directories exist.

        Raises:
            ValueError: If required directories don't exist
        """
        if not self.storage_config.certs_dir.exists():
            raise ValueError(
                f"Certificate directory does not exist: {self.storage_config.certs_dir}. "
                "Ensure nginx-proxy is running and volumes are mounted correctly.",
            )

        if not self.storage_config.ssl_dir.exists():
            raise ValueError(
                f"SSL directory does not exist: {self.storage_config.ssl_dir}. "
                "Ensure nginx-proxy is running and volumes are mounted correctly.",
            )

    def link_certificate(
        self,
        cert_type: str,
        domain: str,
        privkey_path: Path,
        fullchain_path: Path,
        alias_domains: list[str] | None = None,
    ):
        """
        Create symlinks for a certificate and its alias domains.

        This creates symlinks from the certs/ directory to the actual certificate
        files in the ssl/ directory. Both the primary domain and any alias domains
        get their own symlinks pointing to the same certificate files.

        Args:
            cert_type: Type of certificate (e.g., 'letsencrypt', 'self-signed')
            domain: Primary domain name for the certificate
            privkey_path: Path to the private key file (host path)
            fullchain_path: Path to the full chain certificate file (host path)
            alias_domains: Optional list of alias domains that should also point to this cert
        """
        # Convert host paths to container paths for symlink targets
        container_privkey_path = self._host_to_container_path(privkey_path, cert_type)
        container_fullchain_path = self._host_to_container_path(fullchain_path, cert_type)

        primary_privkey_link = self.storage_config.certs_dir / f"{domain}.key"
        primary_fullchain_link = self.storage_config.certs_dir / f"{domain}.crt"

        create_symlink(container_privkey_path, primary_privkey_link)
        create_symlink(container_fullchain_path, primary_fullchain_link)

        if alias_domains:
            for alias_domain in alias_domains:
                alias_privkey_link = self.storage_config.certs_dir / f"{alias_domain}.key"
                alias_fullchain_link = self.storage_config.certs_dir / f"{alias_domain}.crt"

                create_symlink(container_privkey_path, alias_privkey_link)
                create_symlink(container_fullchain_path, alias_fullchain_link)

    def unlink_certificate(self, domain: str, alias_domains: list[str] | None = None):
        """
        Remove symlinks for a certificate and its alias domains.

        Args:
            domain: Primary domain name for the certificate
            alias_domains: Optional list of alias domains to also unlink
        """
        primary_privkey_link = self.storage_config.certs_dir / f"{domain}.key"
        primary_fullchain_link = self.storage_config.certs_dir / f"{domain}.crt"

        self._safe_unlink(primary_privkey_link)
        self._safe_unlink(primary_fullchain_link)

        # Remove alias domain symlinks
        if alias_domains:
            for alias_domain in alias_domains:
                alias_privkey_link = self.storage_config.certs_dir / f"{alias_domain}.key"
                alias_fullchain_link = self.storage_config.certs_dir / f"{alias_domain}.crt"

                self._safe_unlink(alias_privkey_link)
                self._safe_unlink(alias_fullchain_link)

    def get_certificate_paths(self, domain: str) -> tuple[Path, Path]:
        """
        Get the actual certificate file paths by resolving symlinks.

        This follows the symlinks in the certs/ directory to find the actual
        certificate files in the ssl/ directory.

        Args:
            domain: Domain name to get certificate paths for

        Returns:
            Tuple of (privkey_path, fullchain_path) as resolved host paths

        Raises:
            FileNotFoundError: If the certificate symlinks don't exist
        """
        privkey_link = self.storage_config.certs_dir / f"{domain}.key"
        fullchain_link = self.storage_config.certs_dir / f"{domain}.crt"

        # Resolve symlinks to get container paths
        container_privkey_path = privkey_link.readlink()
        container_fullchain_path = fullchain_link.readlink()

        # Convert container paths back to host paths
        privkey_path = self._container_to_host_path(container_privkey_path)
        fullchain_path = self._container_to_host_path(container_fullchain_path)

        return (privkey_path, fullchain_path)

    def _host_to_container_path(self, host_path: Path, cert_type: str) -> Path:
        """
        Convert a host filesystem path to a container filesystem path.

        Args:
            host_path: Path on the host filesystem
            cert_type: Certificate type (e.g., 'letsencrypt')

        Returns:
            Equivalent path as seen from inside the container
        """
        # Calculate relative path from the ssl type directory
        ssl_type_host_dir = self.storage_config.ssl_dir / cert_type
        relative_path = host_path.relative_to(ssl_type_host_dir)

        # Build container path
        container_path = self.storage_config.ssl_dir_container / cert_type / relative_path
        return container_path

    def _container_to_host_path(self, container_path: Path) -> Path:
        """
        Convert a container filesystem path to a host filesystem path.

        Args:
            container_path: Path as seen from inside the container

        Returns:
            Equivalent path on the host filesystem
        """
        # Calculate relative path from the container ssl directory
        relative_path = container_path.relative_to(self.storage_config.ssl_dir_container)

        # Build host path
        host_path = self.storage_config.ssl_dir / relative_path
        return host_path

    def _safe_unlink(self, path: Path):
        """
        Safely remove a symlink, ignoring errors if it doesn't exist.

        Args:
            path: Path to the symlink to remove
        """
        try:
            path.unlink()
        except (FileNotFoundError, OSError):
            # Ignore errors - symlink might already be removed or never existed
            pass
