"""External database TLS material on disk.

Frappe reads TLS from two places and only one of them is per site, so fm writes
two kinds of artefact under the bench's already bind-mounted `config/` tree:

- `config/tls/<site>/db-ca.pem` -- the operator's CA, referenced from
  `sites/<site>/site_config.json` as `db_ssl_ca` for the Python driver, and from
  `config/tls/<site>/my.cnf` for the `mariadb` CLI. fm points `MYSQL_HOME` at
  that directory on the execs it issues itself (new-site, restore, dump,
  `bench mariadb`), which is the narrow, exact-CA path.
- `config/tls/ca-bundle.pem` plus `config/tls/my.cnf` -- every site's CA
  concatenated, for the long-running worker and schedule services. They serve
  the whole bench with one fixed environment and take dumps fm never wraps
  (desk "Download Backup", app-scheduled backups), so they cannot get a per-site
  option file. Hostname verification is still per connection; the bundle only
  widens which CA may sign a given site's server certificate.

Every path written *into* an option file is a container path: the files are read
inside the frappe/worker/schedule containers, never on the host.
"""

import os
import shutil
from pathlib import Path

TLS_CONTAINER_ROOT = "/workspace/frappe-bench/config/tls"

CA_FILE_NAME = "db-ca.pem"
OPTION_FILE_NAME = "my.cnf"
CA_BUNDLE_NAME = "ca-bundle.pem"

_HEADER = "# Generated by fm; do not edit (rewritten whenever a CA is installed or removed).\n"
_PEM_MARKER = "-----BEGIN CERTIFICATE-----"


def site_mysql_home(site: str) -> str:
    """MYSQL_HOME for execs fm issues for one site: exactly that site's CA."""
    return f"{TLS_CONTAINER_ROOT}/{site}"


def bench_mysql_home() -> str:
    """MYSQL_HOME for the bench-wide services (worker, schedule): the bundle."""
    return TLS_CONTAINER_ROOT


def site_ca_container_path(site: str) -> str:
    """Container path of a site's CA, the value of `db_ssl_ca`."""
    return f"{TLS_CONTAINER_ROOT}/{site}/{CA_FILE_NAME}"


def tls_host_root(bench_path: Path) -> Path:
    return bench_path / "workspace" / "frappe-bench" / "config" / "tls"


def site_tls_host_dir(bench_path: Path, site: str) -> Path:
    return tls_host_root(bench_path) / site


def install_site_ca(bench_path: Path, site: str, ca_source: Path) -> str:
    """Copy the operator's CA to config/tls/<site>/db-ca.pem, write that
    directory's my.cnf, refresh the bench bundle. Returns the CONTAINER path
    for db_ssl_ca.

    `db_ssl_check_hostname` is not written here: it is a site_config.json key,
    and the CLI half always verifies via ssl-verify-server-cert.
    """
    source = _validated_ca_source(ca_source)

    site_dir = site_tls_host_dir(bench_path, site)
    site_dir.mkdir(parents=True, exist_ok=True)

    dest = site_dir / CA_FILE_NAME
    # Re-running `fm update --db-ca` with the installed path must not blow up.
    if not (dest.exists() and dest.samefile(source)):
        shutil.copyfile(source, dest)
    dest.chmod(0o644)

    write_site_my_cnf(bench_path, site)
    rebuild_ca_bundle(bench_path)

    return site_ca_container_path(site)


def write_site_my_cnf(bench_path: Path, site: str) -> None:
    """[client] option file for one site, pointing at that site's own CA."""
    site_dir = site_tls_host_dir(bench_path, site)
    site_dir.mkdir(parents=True, exist_ok=True)
    _write_option_file(site_dir / OPTION_FILE_NAME, site_ca_container_path(site))


def rebuild_ca_bundle(bench_path: Path) -> None:
    """Concatenate every config/tls/<site>/db-ca.pem into config/tls/ca-bundle.pem
    and write the bench-level config/tls/my.cnf pointing at it. Used by the
    long-running services (worker/schedule) for dumps fm does not wrap.
    """
    root = tls_host_root(bench_path)
    bundle = root / CA_BUNDLE_NAME
    bench_option_file = root / OPTION_FILE_NAME

    if not root.is_dir():
        return

    # Sorted so an unchanged set of sites always yields a byte-identical bundle.
    pems = []
    for site_dir in sorted(entry for entry in root.iterdir() if entry.is_dir()):
        ca = site_dir / CA_FILE_NAME
        if ca.is_file():
            pems.append(ca.read_text().strip())

    if not pems:
        # An empty ssl-ca file is worse than none: the client fails to load it.
        bundle.unlink(missing_ok=True)
        bench_option_file.unlink(missing_ok=True)
        return

    bundle.write_text("\n".join(pems) + "\n")
    bundle.chmod(0o644)
    _write_option_file(bench_option_file, f"{TLS_CONTAINER_ROOT}/{CA_BUNDLE_NAME}")


def remove_site_tls(bench_path: Path, site: str) -> None:
    """Drop a site's TLS directory and shrink the bundle to the sites that remain."""
    shutil.rmtree(site_tls_host_dir(bench_path, site), ignore_errors=True)
    rebuild_ca_bundle(bench_path)


def _validated_ca_source(ca_source: Path) -> Path:
    """Fail on the operator's own path, before anything is written."""
    if not ca_source.exists():
        raise FileNotFoundError(f"CA file not found: {ca_source}")
    if not ca_source.is_file():
        raise ValueError(f"CA path is not a file: {ca_source}")
    if not os.access(ca_source, os.R_OK):
        raise PermissionError(f"CA file is not readable: {ca_source}")

    content = ca_source.read_text(errors="replace")
    if _PEM_MARKER not in content:
        raise ValueError(
            f"CA file is not PEM (no {_PEM_MARKER!r} block): {ca_source}. "
            "Convert a DER certificate with: openssl x509 -inform der -in <file> -out ca.pem"
        )
    return ca_source


def _write_option_file(path: Path, ca_container_path: str) -> None:
    """A mariadb client option file. Written as plain text: configparser quotes
    bare flags like ssl-verify-server-cert in ways the client does not accept.
    """
    path.write_text(f"{_HEADER}[client]\nssl-ca={ca_container_path}\nssl-verify-server-cert\n")
    path.chmod(0o644)
