"""Manages the Strict-Transport-Security header nginx-proxy sends for a bench's domains.

The bench nginx image hardcodes `add_header Strict-Transport-Security "max-age=...; ...";` in
every site's `listen 80` server block (Docker/nginx/template.conf), unconditionally -- yet the
bench nginx never terminates TLS, only the global nginx-proxy in front of it does. The header
still reaches the browser: nginx-proxy proxies the bench's response back, and by default hides
nothing.

The `hsts` field on `[[ssl.certificates]]` was meant to control this via nginx-proxy's own `HSTS`
env var, but nginx-proxy's template gates its OWN header emission on
`https_method != "noredirect"`, and fm sets `HTTPS_METHOD=noredirect` for every bench
unconditionally (see `BenchConfig.export_to_compose_inputs`) so that fm's own per-domain vhost.d
redirect block -- not nginx-proxy's blunter, all-domains-or-none one -- decides when a domain
force-redirects to HTTPS. That gate is permanently closed for every fm bench, so the env var never
reaches a header at all: `hsts` was dead at both ends, and the bench's hardcoded two-year pin
reached the browser regardless of what it said, "off" included.

Fixed here rather than in nginx-proxy's own template or env: nginx-proxy `include`s
`/etc/nginx/vhost.d/<domain>` inside the per-vhost `server {}` block, before its `location`
blocks and with none of them setting their own `add_header`/`proxy_hide_header` (verified against
the running proxy's own `/app/nginx.tmpl`), so a directive written there is in SERVER context and
applies to every response nginx-proxy sends for that domain, including the ones proxied back from
the bench -- which is exactly what is needed to strip the bench's hardcoded header and, unless the
operator asked for "off", replace it with the configured one. This reaches every EXISTING bench
with no image rebuild, no compose tag bump and no nginx re-render: nginx-proxy re-reads vhost.d
on its own reload, which every caller of `set_hsts`/`remove_hsts` already triggers when it changes
anything (see `Bench.apply_hsts`).
"""

import re
from pathlib import Path


class HstsManager:
    """Writes/removes fm's `# fm:hsts` marked block in a domain's nginx-proxy vhost.d file.

    The file is SHARED: `UploadLimitManager` appends a `client_max_body_size` directive to it,
    `fm maintenance` owns a `# fm:maintenance` block in it, `VhostConfigManager` owns a
    `# fm:https-redirect` block in it, and an operator may hand-write directives into it too. So
    this owns its own marked block and never touches anything else in the file -- the same shape
    `VhostConfigManager` uses for its block, applied to a second, independent concern.
    """

    BLOCK_BEGIN = "# fm:hsts BEGIN"
    BLOCK_END = "# fm:hsts END"
    _BLOCK_RE = re.compile(r"^# fm:hsts BEGIN.*?^# fm:hsts END\n?", re.DOTALL | re.MULTILINE)

    def __init__(self, vhostd_dir: Path):
        self.vhostd_dir = vhostd_dir

    @classmethod
    def _block(cls, value: str) -> str:
        """The block body for `value` (an STS header value, or "off").

        `proxy_hide_header` is unconditional, "off" included, and NOT keyed on `$https`: the
        bench emits its hardcoded header on every response regardless of scheme, so hiding it
        must not become scheme-dependent either, or an operator who asked for no HSTS would still
        receive the bench's own two-year pin on an http:// response too.

        `add_header`, when added, IS keyed on `$https` -- RFC 6797 requires a host not send this
        header over a non-secure connection, and this vhost's `server {}` block (see module
        docstring) has both a `listen 80` and a `listen ... ssl` in it, so it answers both. Empty
        assignment is nginx-proxy's OWN idiom for exactly this, read off its running container's
        `/app/nginx.tmpl` next to its `$sts_header`: `add_header` with an empty value omits the
        header entirely (nginx docs), so this needs no `if` around the `add_header` itself -- an
        `if` inside a location is the classic nginx footgun; this one lives in server context,
        matching where nginx-proxy's own copy of the same idiom lives, and `$https` is a core
        `ngx_http_core_module` variable, always defined in any http context.
        """
        lines = [
            cls.BLOCK_BEGIN,
            "# generated by fm; do not edit -- bench nginx always sends its own hardcoded",
            "# Strict-Transport-Security, so it is always hidden here (any scheme) and replaced,",
            '# over https only, with the configured value unless hsts is "off"',
            "proxy_hide_header Strict-Transport-Security;",
        ]
        if value.strip().lower() != "off":
            lines += [
                'set $fm_hsts_value "";',
                "if ($https) {",
                f'    set $fm_hsts_value "{value}";',
                "}",
                "add_header Strict-Transport-Security $fm_hsts_value always;",
            ]
        lines.append(cls.BLOCK_END)
        return "\n".join(lines) + "\n"

    def set_hsts(self, domain: str, value: str) -> bool:
        """Write/refresh the block for `domain`.

        Replaces only fm's own block; everything else already in this shared file survives
        verbatim. Returns True when the file's bytes changed, so a caller can reload nginx-proxy
        only when something actually did.
        """
        vhost_file = self.vhostd_dir / domain
        existing = vhost_file.read_text() if vhost_file.exists() else ""
        remainder = self._BLOCK_RE.sub("", existing)
        new_content = self._block(value) + remainder
        if new_content == existing:
            return False
        vhost_file.write_text(new_content)
        return True

    def remove_hsts(self, domain: str) -> None:
        """Strip fm's block, leaving foreign content in place -- byte-for-byte, not merely
        semantically equal, mirroring `VhostConfigManager.disable_https_redirect`.

        The file itself is deleted only when removing the block empties it. Deliberately a
        truthy check on the exact remainder, not `.strip()`: a remainder that is pure whitespace
        (a foreign file that was only ever a blank line) is still real bytes this call did not
        put there, and `.strip()` treated it as empty and unlinked the file, so add-then-remove
        was not a true inverse of a shared file whose only foreign content was blank lines around
        fm's own block.
        """
        vhost_file = self.vhostd_dir / domain
        if not vhost_file.exists():
            return

        text = vhost_file.read_text()
        if self.BLOCK_BEGIN not in text:
            return

        remainder = self._BLOCK_RE.sub("", text)
        if remainder:
            vhost_file.write_text(remainder)
        else:
            vhost_file.unlink()
