"""Real client IP restoration (ngx_http_realip_module) conf rendering.

Two hops need it:
- bench nginx always sees the global proxy's frontend-network address, so it
  trusts that subnet and restores the client from X-Real-IP (which the proxy
  sets from its own, possibly CDN-corrected, remote_addr);
- the global nginx-proxy only needs it behind a CDN or external load
  balancer, where remote_addr is the CDN edge and the client is in a header.
"""

import ipaddress
from pathlib import Path

_MARKER = "# fm:real-ip"
_TRUST_MARKER = "# fm:forwarded-trust"

# The overlay `fm services trusted-proxies` maintains in the global proxy's conf.d.
PROXY_CONF_FILENAME = "fm-real-ip.conf"

# The second file that overlay drives: the scheme decision and the published HTTPS port, both
# read by fm's own redirect blocks. Separate from the real-ip conf because it must exist even
# when nothing is trusted -- `$fm_client_scheme` has to be defined for every host, or the
# per-domain redirect blocks fail to parse and the proxy refuses to start.
PROXY_TRUST_CONF_FILENAME = "fm-forwarded-trust.conf"

# Published Cloudflare edge ranges (https://www.cloudflare.com/ips/), vendored
# as a fallback for when the live fetch is unavailable.
CLOUDFLARE_IPS_URLS = ("https://www.cloudflare.com/ips-v4", "https://www.cloudflare.com/ips-v6")
CLOUDFLARE_FALLBACK_RANGES = [
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22",
    "2400:cb00::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2405:b500::/32",
    "2405:8100::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32",
]


def validate_cidrs(ranges: list[str]) -> list[str]:
    """Normalize and validate CIDR blocks / bare addresses; raises ValueError
    naming the offending entry."""
    normalized = []
    for entry in ranges:
        try:
            normalized.append(str(ipaddress.ip_network(entry, strict=False)))
        except ValueError as e:
            raise ValueError(f"invalid IP range {entry!r}: {e}") from e
    return normalized


def build_bench_realip_conf(subnet_cidr: str) -> str:
    """Bench nginx: trust the fm frontend network (the only route in) and
    take the client address from X-Real-IP set by the global proxy."""
    return (
        f"{_MARKER} generated by fm; do not edit (regenerated with the bench compose)\n"
        f"set_real_ip_from {subnet_cidr};\n"
        "real_ip_header X-Real-IP;\n"
    )


def build_proxy_realip_conf(ranges: list[str], header: str, recursive: bool) -> str:
    """Global nginx-proxy: trust the CDN/LB ranges and take the client address
    from the header that edge sets."""
    lines = [f"{_MARKER} generated by `fm services trusted-proxies`; do not edit"]
    lines += [f"set_real_ip_from {r};" for r in ranges]
    lines.append(f"real_ip_header {header};")
    if recursive:
        lines.append("real_ip_recursive on;")
    return "\n".join(lines) + "\n"


def build_proxy_trust_conf(ranges: list[str], https_suffix: str) -> str:
    """The scheme decision and the published HTTPS port, for fm's own redirect blocks.

    `geo`, not `map`: `map` matches exact strings and regexes, never CIDRs. Keyed on
    `$realip_remote_addr` rather than `$remote_addr` because that is the peer BEFORE
    `set_real_ip_from` rewrites the address to the real client -- so it stays the edge, which is
    the whole point of asking.

    The default arm is `$scheme`, the connection fm actually received. A forwarded header from an
    untrusted peer therefore changes nothing, which is what makes the redirect unforgeable on a
    host with no front (and on any request that did not come through one).
    """
    lines = [
        f"{_TRUST_MARKER} generated by `fm services trusted-proxies`; do not edit",
        "geo $realip_remote_addr $fm_peer_trusted {",
        "    default 0;",
    ]
    lines += [f"    {r} 1;" for r in ranges]
    lines += [
        "}",
        'map "$fm_peer_trusted:$http_x_forwarded_proto" $fm_client_scheme {',
        "    default   $scheme;",
        '    "1:https" https;',
        '    "1:http"  http;',
        "}",
        "map $host $fm_https_suffix {",
        f'    default "{https_suffix}";',
        "}",
    ]
    return "\n".join(lines) + "\n"


def trusted_ranges(confd_dir: Path) -> list[str]:
    """CIDRs currently trusted on this host; `[]` when nothing is configured.

    Read back from the rendered conf rather than a config key: that file is the single source of
    truth for the trusted set, and a second copy in fm_config.toml could disagree with what nginx
    is actually running.
    """
    conf = confd_dir / PROXY_CONF_FILENAME
    if not conf.is_file():
        return []
    text = conf.read_text()
    if not is_fm_realip_conf(text):
        return []
    return [
        line.removeprefix("set_real_ip_from ").rstrip(";").strip()
        for line in text.splitlines()
        if line.startswith("set_real_ip_from ")
    ]


def is_fm_realip_conf(text: str) -> bool:
    return text.startswith(_MARKER)


def summarize_proxy_realip_conf(text: str) -> str | None:
    """One-line summary of an fm-written proxy real-ip conf ("trusting N range(s),
    restoring client IP from H"); ``None`` for foreign or non-fm content, so callers
    never describe a hand-written file as fm's."""
    if not is_fm_realip_conf(text):
        return None
    lines = text.splitlines()
    ranges = [line for line in lines if line.startswith("set_real_ip_from ")]
    header = next(
        (line.removeprefix("real_ip_header ").rstrip(";").strip() for line in lines if line.startswith("real_ip_header ")),
        None,
    )
    return f"trusting {len(ranges)} range(s), restoring client IP from {header or 'an unknown header'}"
