"""Real client IP restoration (ngx_http_realip_module) conf rendering.

Two hops need it:
- bench nginx always sees the global proxy's frontend-network address, so it
  trusts that subnet and restores the client from X-Real-IP (which the proxy
  sets from its own, possibly CDN-corrected, remote_addr);
- the global nginx-proxy only needs it behind a CDN or external load
  balancer, where remote_addr is the CDN edge and the client is in a header.
"""

import ipaddress

_MARKER = "# fm:real-ip"

# Published Cloudflare edge ranges (https://www.cloudflare.com/ips/), vendored
# as a fallback for when the live fetch is unavailable.
CLOUDFLARE_IPS_URLS = ("https://www.cloudflare.com/ips-v4", "https://www.cloudflare.com/ips-v6")
CLOUDFLARE_FALLBACK_RANGES = [
    "173.245.48.0/20",
    "103.21.244.0/22",
    "103.22.200.0/22",
    "103.31.4.0/22",
    "141.101.64.0/18",
    "108.162.192.0/18",
    "190.93.240.0/20",
    "188.114.96.0/20",
    "197.234.240.0/22",
    "198.41.128.0/17",
    "162.158.0.0/15",
    "104.16.0.0/13",
    "104.24.0.0/14",
    "172.64.0.0/13",
    "131.0.72.0/22",
    "2400:cb00::/32",
    "2606:4700::/32",
    "2803:f800::/32",
    "2405:b500::/32",
    "2405:8100::/32",
    "2a06:98c0::/29",
    "2c0f:f248::/32",
]


def validate_cidrs(ranges: list[str]) -> list[str]:
    """Normalize and validate CIDR blocks / bare addresses; raises ValueError
    naming the offending entry."""
    normalized = []
    for entry in ranges:
        try:
            normalized.append(str(ipaddress.ip_network(entry, strict=False)))
        except ValueError as e:
            raise ValueError(f"invalid IP range {entry!r}: {e}") from e
    return normalized


def build_bench_realip_conf(subnet_cidr: str) -> str:
    """Bench nginx: trust the fm frontend network (the only route in) and
    take the client address from X-Real-IP set by the global proxy."""
    return (
        f"{_MARKER} generated by fm; do not edit (regenerated with the bench compose)\n"
        f"set_real_ip_from {subnet_cidr};\n"
        "real_ip_header X-Real-IP;\n"
    )


def build_proxy_realip_conf(ranges: list[str], header: str, recursive: bool) -> str:
    """Global nginx-proxy: trust the CDN/LB ranges and take the client address
    from the header that edge sets."""
    lines = [f"{_MARKER} generated by `fm self real-ip`; do not edit"]
    lines += [f"set_real_ip_from {r};" for r in ranges]
    lines.append(f"real_ip_header {header};")
    if recursive:
        lines.append("real_ip_recursive on;")
    return "\n".join(lines) + "\n"


def is_fm_realip_conf(text: str) -> bool:
    return text.startswith(_MARKER)
