"""Contract of `frappe_manager/ssl_manager/vhost_config_manager.py`.

The nginx-proxy `vhost.d/<domain>` file is SHARED: `fm maintenance` owns a marked
`# fm:maintenance BEGIN/END` block in it, `UploadLimitManager` appends a
`client_max_body_size` directive to it, and operators hand-write directives into it. So
enabling/disabling the HTTPS redirect must edit only fm's own redirect block.
"""

from pathlib import Path

import pytest

from frappe_manager.ssl_manager.vhost_config_manager import VhostConfigManager

DOMAIN = "example.com"

MAINTENANCE_BLOCK = """# fm:maintenance BEGIN (bench: mybench) generated by `fm maintenance`; do not edit this block
set $fm_maintenance 1;
# fm:maintenance END
"""
UPLOAD_LIMIT = "client_max_body_size 512m;"
HANDWRITTEN = "add_header X-Operator-Wrote-This 1;"


@pytest.fixture
def vhostd(tmp_path: Path) -> Path:
    d = tmp_path / "vhostd"
    d.mkdir()
    return d


@pytest.fixture
def manager(vhostd: Path) -> VhostConfigManager:
    return VhostConfigManager(vhostd)


def test_missing_vhostd_directory_is_rejected_at_construction(tmp_path: Path):
    with pytest.raises(ValueError, match=r"vhost\.d directory does not exist"):
        VhostConfigManager(tmp_path / "nope")


def test_enable_creates_the_file_with_the_marked_redirect_block(manager, vhostd):
    path = manager.enable_https_redirect(DOMAIN)

    assert path == vhostd / DOMAIN
    text = path.read_text()
    assert text.startswith(VhostConfigManager.BLOCK_BEGIN + "\n")
    assert text.rstrip("\n").endswith(VhostConfigManager.BLOCK_END)
    assert "return 301 https://$host$request_uri;" in text
    assert manager.has_redirect_config(DOMAIN)


def test_enable_and_disable_preserve_foreign_content_in_the_shared_file(manager, vhostd):
    """Regression: enable used to `write_text()` the whole file and disable used to unlink it,
    silently taking a bench out of maintenance and resetting the proxy upload limit."""
    path = vhostd / DOMAIN
    path.write_text(MAINTENANCE_BLOCK + UPLOAD_LIMIT + "\n" + HANDWRITTEN + "\n")

    manager.enable_https_redirect(DOMAIN)

    after_enable = path.read_text()
    assert "# fm:maintenance BEGIN" in after_enable
    assert "# fm:maintenance END" in after_enable
    assert "set $fm_maintenance 1;" in after_enable
    assert UPLOAD_LIMIT in after_enable
    assert HANDWRITTEN in after_enable
    assert VhostConfigManager.BLOCK_BEGIN in after_enable

    assert manager.disable_https_redirect(DOMAIN) is True

    after_disable = path.read_text()
    assert "# fm:maintenance BEGIN" in after_disable
    assert "set $fm_maintenance 1;" in after_disable
    assert UPLOAD_LIMIT in after_disable
    assert HANDWRITTEN in after_disable
    # only fm's own block is gone
    assert VhostConfigManager.BLOCK_BEGIN not in after_disable
    assert "return 301 https://$host$request_uri;" not in after_disable
    assert manager.has_redirect_config(DOMAIN) is False


def test_enable_is_idempotent_and_never_stacks_duplicate_blocks(manager, vhostd):
    path = vhostd / DOMAIN
    path.write_text(UPLOAD_LIMIT + "\n")

    manager.enable_https_redirect(DOMAIN)
    first = path.read_text()
    manager.enable_https_redirect(DOMAIN)

    assert path.read_text() == first
    assert first.count(VhostConfigManager.BLOCK_BEGIN) == 1
    assert first.count(UPLOAD_LIMIT) == 1


def test_disable_removes_the_file_when_nothing_else_remains(manager, vhostd):
    manager.enable_https_redirect(DOMAIN)

    assert manager.disable_https_redirect(DOMAIN) is True
    assert not (vhostd / DOMAIN).exists()


def test_disable_on_a_file_without_our_block_changes_nothing(manager, vhostd):
    path = vhostd / DOMAIN
    path.write_text(UPLOAD_LIMIT + "\n")

    assert manager.disable_https_redirect(DOMAIN) is False
    assert path.read_text() == UPLOAD_LIMIT + "\n"


def test_disable_on_a_missing_file_reports_false(manager):
    assert manager.disable_https_redirect(DOMAIN) is False
    assert manager.has_redirect_config(DOMAIN) is False


def test_legacy_unmarked_redirect_file_can_still_be_disabled(manager, vhostd):
    """Installs upgraded from the write_text() era hold the bare config with no markers;
    disable must still turn the redirect off there."""
    path = vhostd / DOMAIN
    path.write_text(VhostConfigManager.HTTPS_REDIRECT_CONFIG)

    assert manager.has_redirect_config(DOMAIN) is True
    assert manager.disable_https_redirect(DOMAIN) is True
    assert not path.exists()


def test_legacy_unmarked_redirect_is_replaced_by_the_marked_block_on_enable(manager, vhostd):
    path = vhostd / DOMAIN
    path.write_text(VhostConfigManager.HTTPS_REDIRECT_CONFIG + UPLOAD_LIMIT + "\n")

    manager.enable_https_redirect(DOMAIN)

    text = path.read_text()
    assert text.count("return 301 https://$host$request_uri;") == 1
    assert text.count(VhostConfigManager.BLOCK_BEGIN) == 1
    assert UPLOAD_LIMIT in text


def test_get_config_path_points_at_the_per_domain_file(manager, vhostd):
    assert manager.get_config_path(DOMAIN) == vhostd / DOMAIN


# ======================================================================================
# enable then disable is a true inverse -- byte-for-byte, not merely semantically equal
# ======================================================================================


def test_add_then_remove_restores_a_brand_new_domain_to_no_file_at_all(manager, vhostd):
    path = vhostd / DOMAIN
    assert not path.exists()

    manager.enable_https_redirect(DOMAIN)
    assert manager.disable_https_redirect(DOMAIN) is True

    assert not path.exists()


@pytest.mark.parametrize(
    "original",
    [
        UPLOAD_LIMIT + "\n",
        MAINTENANCE_BLOCK + UPLOAD_LIMIT + "\n" + HANDWRITTEN + "\n",
        # The exact production shape this was found against: a leading blank line before the
        # first real directive.
        "\n" + HANDWRITTEN + "\n",
        # Trailing blank line, no leading one.
        UPLOAD_LIMIT + "\n\n",
        # No trailing newline at all.
        HANDWRITTEN,
    ],
    ids=["plain", "maintenance+upload+handwritten", "leading-blank-line", "trailing-blank-line", "no-trailing-newline"],
)
def test_add_then_remove_restores_the_shared_file_byte_for_byte(manager, vhostd, original):
    path = vhostd / DOMAIN
    path.write_text(original)
    before = path.read_bytes()

    manager.enable_https_redirect(DOMAIN)
    assert path.read_bytes() != before  # sanity: enable actually changed the file
    assert manager.disable_https_redirect(DOMAIN) is True

    assert path.read_bytes() == before


def test_add_then_remove_restores_the_legacy_unmarked_shape_byte_for_byte(manager, vhostd):
    """The one real shape this file must never break: a pre-markers install whose whole file body
    is the bare config, no markers, verified against a production host and against this machine.
    `enable` upgrades it to the marked form; `disable` must still return it to nothing (the whole
    body was fm's own text, so 'restored' means the file is gone, matching what a legacy `disable`
    on that same file, without ever calling enable first, already does)."""
    path = vhostd / DOMAIN
    path.write_text(VhostConfigManager.HTTPS_REDIRECT_CONFIG)

    manager.enable_https_redirect(DOMAIN)
    assert manager.disable_https_redirect(DOMAIN) is True

    assert not path.exists()


def test_disable_alone_on_the_legacy_unmarked_shape_leaves_no_empty_file_behind(manager, vhostd):
    """Regression: the bare exact-text match used to leave the constant's own trailing newline
    behind as a truthy 'remainder', so disable kept an empty file around instead of deleting it."""
    path = vhostd / DOMAIN
    path.write_text(VhostConfigManager.HTTPS_REDIRECT_CONFIG)

    assert manager.disable_https_redirect(DOMAIN) is True

    assert not path.exists()


# ======================================================================================
# --behind-proxy variant: keyed on the forwarded proto, not the origin's own connection scheme
# ======================================================================================


def test_behind_proxy_enable_writes_the_forwarded_proto_predicate(manager, vhostd):
    path = manager.enable_https_redirect(DOMAIN, behind_proxy=True)

    text = path.read_text()
    assert text.startswith(VhostConfigManager.BLOCK_BEGIN + "\n")
    assert text.rstrip("\n").endswith(VhostConfigManager.BLOCK_END)
    assert "if ($proxy_x_forwarded_proto = http)" in text
    # Not the connection-scheme predicate: behind an external terminator this connection is
    # always plain http, and keying off $scheme here is exactly the infinite-redirect bug.
    assert "if ($scheme = http)" not in text
    assert "return 301 https://$host$request_uri;" in text
    assert manager.has_redirect_config(DOMAIN)


def test_behind_proxy_variant_keeps_the_realtime_exemption_verbatim(manager, vhostd):
    """The websocket/realtime carve-out is copied unchanged into the new variant: Node's fetch()
    drops Cookie headers on cross-protocol redirects regardless of which predicate sent it there."""
    path = manager.enable_https_redirect(DOMAIN, behind_proxy=True)

    text = path.read_text()
    assert r"if ($uri ~ ^/api/method/frappe\.realtime\.) {" in text
    # The exemption clears the flag the http-check just set, exactly as the default variant does.
    default_text = VhostConfigManager.HTTPS_REDIRECT_CONFIG
    behind_proxy_text = VhostConfigManager.HTTPS_REDIRECT_CONFIG_BEHIND_PROXY
    default_exemption = default_text.split("if ($uri", 1)[1]
    behind_proxy_exemption = behind_proxy_text.split("if ($uri", 1)[1]
    assert default_exemption == behind_proxy_exemption


def test_default_https_redirect_config_text_is_untouched_by_this_variant(manager):
    """CRITICAL regression guard: real deployed benches carry HTTPS_REDIRECT_CONFIG unmarked (see
    _LEGACY_RE), so its text must stay byte-identical to before this variant was added -- a single
    character of drift here breaks legacy-file removal on every bench that predates the markers."""
    assert VhostConfigManager.HTTPS_REDIRECT_CONFIG == (
        "# Enable HTTPS redirect for this domain only\n"
        "# This domain has a valid SSL certificate\n"
        "# Internal service API calls allowed over HTTP (Cookie header lost on redirect)\n"
        "set $redirect_to_https 0;\n"
        "if ($scheme = http) {\n"
        "    set $redirect_to_https 1;\n"
        "}\n"
        "if ($uri ~ ^/api/method/frappe\\.realtime\\.) {\n"
        "    set $redirect_to_https 0;\n"
        "}\n"
        "if ($redirect_to_https = 1) {\n"
        "    return 301 https://$host$request_uri;\n"
        "}\n"
    )


def test_behind_proxy_add_then_remove_restores_the_shared_file_byte_for_byte(manager, vhostd):
    """Same byte-faithful inverse guarantee as the default variant, proven for this one too: the
    marker-based strip does not care which body was between BEGIN and END."""
    path = vhostd / DOMAIN
    original = MAINTENANCE_BLOCK + UPLOAD_LIMIT + "\n" + HANDWRITTEN + "\n"
    path.write_text(original)
    before = path.read_bytes()

    manager.enable_https_redirect(DOMAIN, behind_proxy=True)
    assert path.read_bytes() != before
    assert manager.disable_https_redirect(DOMAIN) is True

    assert path.read_bytes() == before


def test_behind_proxy_add_then_remove_on_a_brand_new_domain_leaves_no_file(manager, vhostd):
    path = vhostd / DOMAIN

    manager.enable_https_redirect(DOMAIN, behind_proxy=True)
    assert manager.disable_https_redirect(DOMAIN) is True

    assert not path.exists()


def test_re_enabling_with_the_other_variant_replaces_rather_than_stacks(manager, vhostd):
    """An operator re-running `fm ssl add` with a different --behind-proxy choice for the same
    domain must not end up with two competing redirect blocks in one file."""
    manager.enable_https_redirect(DOMAIN, behind_proxy=False)
    manager.enable_https_redirect(DOMAIN, behind_proxy=True)

    text = (vhostd / DOMAIN).read_text()
    assert text.count(VhostConfigManager.BLOCK_BEGIN) == 1
    assert "if ($proxy_x_forwarded_proto = http)" in text
    assert "if ($scheme = http)" not in text


def test_disable_removes_a_behind_proxy_block_the_same_way_as_the_default(manager, vhostd):
    """`disable_https_redirect` takes no `behind_proxy` parameter and needs none: both variants
    live inside the same BLOCK markers, so the marker-based removal strips either one."""
    manager.enable_https_redirect(DOMAIN, behind_proxy=True)

    assert manager.disable_https_redirect(DOMAIN) is True
    assert not (vhostd / DOMAIN).exists()
    assert manager.has_redirect_config(DOMAIN) is False
