"""Contract of `frappe_manager/ssl_manager/vhost_config_manager.py`.

The nginx-proxy `vhost.d/<domain>` file is SHARED: `fm maintenance` owns a marked
`# fm:maintenance BEGIN/END` block in it, `UploadLimitManager` appends a
`client_max_body_size` directive to it, and operators hand-write directives into it. So
enabling/disabling the HTTPS redirect must edit only fm's own redirect block.
"""

from pathlib import Path

import pytest

from frappe_manager.ssl_manager.vhost_config_manager import VhostConfigManager

DOMAIN = "example.com"

MAINTENANCE_BLOCK = """# fm:maintenance BEGIN (bench: mybench) generated by `fm maintenance`; do not edit this block
set $fm_maintenance 1;
# fm:maintenance END
"""
UPLOAD_LIMIT = "client_max_body_size 512m;"
HANDWRITTEN = "add_header X-Operator-Wrote-This 1;"


@pytest.fixture
def vhostd(tmp_path: Path) -> Path:
    d = tmp_path / "vhostd"
    d.mkdir()
    return d


@pytest.fixture
def manager(vhostd: Path) -> VhostConfigManager:
    return VhostConfigManager(vhostd)


def test_missing_vhostd_directory_is_rejected_at_construction(tmp_path: Path):
    with pytest.raises(ValueError, match=r"vhost\.d directory does not exist"):
        VhostConfigManager(tmp_path / "nope")


def test_enable_creates_the_file_with_the_marked_redirect_block(manager, vhostd):
    path = manager.enable_https_redirect(DOMAIN)

    assert path == vhostd / DOMAIN
    text = path.read_text()
    assert text.startswith(VhostConfigManager.BLOCK_BEGIN + "\n")
    assert text.rstrip("\n").endswith(VhostConfigManager.BLOCK_END)
    assert "return 301 https://$host$request_uri;" in text
    assert manager.has_redirect_config(DOMAIN)


def test_enable_and_disable_preserve_foreign_content_in_the_shared_file(manager, vhostd):
    """Regression: enable used to `write_text()` the whole file and disable used to unlink it,
    silently taking a bench out of maintenance and resetting the proxy upload limit."""
    path = vhostd / DOMAIN
    path.write_text(MAINTENANCE_BLOCK + UPLOAD_LIMIT + "\n" + HANDWRITTEN + "\n")

    manager.enable_https_redirect(DOMAIN)

    after_enable = path.read_text()
    assert "# fm:maintenance BEGIN" in after_enable
    assert "# fm:maintenance END" in after_enable
    assert "set $fm_maintenance 1;" in after_enable
    assert UPLOAD_LIMIT in after_enable
    assert HANDWRITTEN in after_enable
    assert VhostConfigManager.BLOCK_BEGIN in after_enable

    assert manager.disable_https_redirect(DOMAIN) is True

    after_disable = path.read_text()
    assert "# fm:maintenance BEGIN" in after_disable
    assert "set $fm_maintenance 1;" in after_disable
    assert UPLOAD_LIMIT in after_disable
    assert HANDWRITTEN in after_disable
    # only fm's own block is gone
    assert VhostConfigManager.BLOCK_BEGIN not in after_disable
    assert "return 301 https://$host$request_uri;" not in after_disable
    assert manager.has_redirect_config(DOMAIN) is False


def test_enable_is_idempotent_and_never_stacks_duplicate_blocks(manager, vhostd):
    path = vhostd / DOMAIN
    path.write_text(UPLOAD_LIMIT + "\n")

    manager.enable_https_redirect(DOMAIN)
    first = path.read_text()
    manager.enable_https_redirect(DOMAIN)

    assert path.read_text() == first
    assert first.count(VhostConfigManager.BLOCK_BEGIN) == 1
    assert first.count(UPLOAD_LIMIT) == 1


def test_disable_removes_the_file_when_nothing_else_remains(manager, vhostd):
    manager.enable_https_redirect(DOMAIN)

    assert manager.disable_https_redirect(DOMAIN) is True
    assert not (vhostd / DOMAIN).exists()


def test_disable_on_a_file_without_our_block_changes_nothing(manager, vhostd):
    path = vhostd / DOMAIN
    path.write_text(UPLOAD_LIMIT + "\n")

    assert manager.disable_https_redirect(DOMAIN) is False
    assert path.read_text() == UPLOAD_LIMIT + "\n"


def test_disable_on_a_missing_file_reports_false(manager):
    assert manager.disable_https_redirect(DOMAIN) is False
    assert manager.has_redirect_config(DOMAIN) is False


def test_legacy_unmarked_redirect_file_can_still_be_disabled(manager, vhostd):
    """Installs upgraded from the write_text() era hold the bare config with no markers;
    disable must still turn the redirect off there."""
    path = vhostd / DOMAIN
    path.write_text(VhostConfigManager.HTTPS_REDIRECT_CONFIG)

    assert manager.has_redirect_config(DOMAIN) is True
    assert manager.disable_https_redirect(DOMAIN) is True
    assert not path.exists()


def test_legacy_unmarked_redirect_is_replaced_by_the_marked_block_on_enable(manager, vhostd):
    path = vhostd / DOMAIN
    path.write_text(VhostConfigManager.HTTPS_REDIRECT_CONFIG + UPLOAD_LIMIT + "\n")

    manager.enable_https_redirect(DOMAIN)

    text = path.read_text()
    assert text.count("return 301 https://$host$request_uri;") == 1
    assert text.count(VhostConfigManager.BLOCK_BEGIN) == 1
    assert UPLOAD_LIMIT in text


def test_get_config_path_points_at_the_per_domain_file(manager, vhostd):
    assert manager.get_config_path(DOMAIN) == vhostd / DOMAIN
