"""Site Manager Module - Configuration and Constants"""

__all__ = [
    "VSCODE_LAUNCH_JSON",
    "VSCODE_TASKS_JSON",
    "VSCODE_SETTINGS_JSON",
    "NVIM_DAP_LUA",
    "PREBAKED_SITE_APPS",
    "NON_BASH_SUPPORTED_SERVICES",
]

VSCODE_LAUNCH_JSON = {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "fm-frappe-debug",
            "type": "debugpy",
            "request": "launch",
            "program": "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
            "preLaunchTask": "fm-kill-port",
            "args": ["frappe", "serve", "--port", "80", "--noreload", "--nothreading"],
            "cwd": "/workspace/frappe-bench/sites",
            "consoleName": "Frappe Debug",
            "env": {"DEV_SERVER": "1"},
            "justMyCode": False,
        },
        {
            "name": "Debug Specific Queue",
            "type": "debugpy",
            "request": "launch",
            "program": "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
            "args": [
                "frappe",
                "worker",
                "--queue",
                "${input:queue}",
            ],
            "consoleName": "${input:queue} worker",
            "cwd": "/workspace/frappe-bench/sites",
        },
        {
            "name": "Debug specific fuction",
            "type": "debugpy",
            "request": "launch",
            "program": "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
            "cwd": "/workspace/frappe-bench/sites",
            "args": [
                "frappe",
                "execute",
                "${input:executable_path}",
            ],
            "consoleName": "Frappe Function",
        },
    ],
    "inputs": [
        {
            "id": "queue",
            "type": "command",
            "command": "extension.commandvariable.promptStringRemember",
            "args": {
                "key": "frappe_queue_name",
                "description": "Enter the queue name to debug.",
            },
        },
        {
            "id": "executable_path",
            "type": "command",
            "command": "extension.commandvariable.promptStringRemember",
            "args": {
                "key": "frappe_executable_path",
                "description": "Enter the path to frappe executable function",
            },
        },
    ],
}

VSCODE_TASKS_JSON = {
    "version": "2.0.0",
    "tasks": [
        {
            "label": "fm-kill-port",
            "type": "shell",
            "command": "/bin/bash",
            "args": ["-c", "fmx stop frappe && sleep 2"],
            "presentation": {"reveal": "never", "panel": "dedicated"},
            "options": {"ignoreExitCode": True},
            "problemMatcher": [],
        },
    ],
}

VSCODE_SETTINGS_JSON = {
    "python.defaultInterpreterPath": "/workspace/frappe-bench/env/bin/python",
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.formatOnSave": True,
        "editor.codeActionsOnSave": {"source.fixAll": True, "source.organizeImports": True},
        "editor.detectIndentation": True,
        "editor.tabSize": 4,
        "editor.insertSpaces": True,
    },
    "ruff.organizeImports": True,
    "ruff.fixAll": True,
    "ruff.lint.run": "onSave",
}

# Lua configuration for nvim-dap (Neovim Debug Adapter Protocol).
# Written as a .nvim.lua project-local file so nvim-dap picks it up
# automatically when the workspace is opened inside the container.
#
# Prerequisites (install in your Neovim config):
#   - mfussenegger/nvim-dap
#   - mfussenegger/nvim-dap-python  (optional but recommended)
# Add to config:
# vim.opt.exrc = true   -- load .nvim.lua from project root (Neovim ≥ 0.9: requires :trust)
#
# The three configurations mirror the VS Code launch.json exactly:
#   1. fm-frappe-debug      -- serves Frappe on port 80 with debugpy attached
#   2. Debug Specific Queue -- attach debugpy to a specific background worker
#   3. Debug Specific Function -- run a single frappe.execute() call under debugpy
#
# The pre-launch hook for fm-frappe-debug runs `fmx stop frappe && sleep 2`
# inside the container (equivalent to the VS Code fm-kill-port task) so the
# port is free before the debug server starts.
NVIM_DAP_LUA = """-- .nvim.lua  –  Frappe-Manager nvim-dap configuration
-- Generated by `fm nvim --debugger`. Do not edit manually.
-- Requires: mfussenegger/nvim-dap  (and optionally mfussenegger/nvim-dap-python)

local dap = require("dap")

-- ---------------------------------------------------------------------------
-- Adapter: debugpy running inside the frappe container
-- ---------------------------------------------------------------------------
dap.adapters.debugpy = {
  type = "executable",
  command = "/workspace/frappe-bench/env/bin/python",
  args = { "-m", "debugpy.adapter" },
}

-- ---------------------------------------------------------------------------
-- Helper: kill the Frappe web-server before starting a debug session
-- (mirrors the fm-kill-port VS Code pre-launch task)
-- ---------------------------------------------------------------------------
local function fm_kill_port(callback)
  vim.notify("[fm] stopping frappe service before debug session…", vim.log.levels.INFO)
  local job = vim.fn.jobstart(
    { "/bin/bash", "-c", "fmx stop frappe && sleep 2" },
    {
      on_exit = function(_, code)
        if code ~= 0 then
          vim.notify("[fm] fmx stop frappe exited with code " .. code, vim.log.levels.WARN)
        end
        callback()
      end,
    }
  )
  if job <= 0 then
    vim.notify("[fm] could not start fmx stop frappe", vim.log.levels.ERROR)
    callback()
  end
end

-- ---------------------------------------------------------------------------
-- Configurations
-- ---------------------------------------------------------------------------
dap.configurations.python = dap.configurations.python or {}

-- 1. Frappe dev-server debug session
table.insert(dap.configurations.python, {
  name    = "fm-frappe-debug",
  type    = "debugpy",
  request = "launch",
  program = "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
  args    = { "frappe", "serve", "--port", "80", "--noreload", "--nothreading" },
  cwd     = "/workspace/frappe-bench/sites",
  env     = { DEV_SERVER = "1" },
  justMyCode = false,
  -- Kill the port before the session starts (mirrors preLaunchTask)
  before_session_start = function(callback)
    fm_kill_port(callback)
  end,
})

-- 2. Debug a specific background worker queue
table.insert(dap.configurations.python, {
  name    = "Debug Specific Queue",
  type    = "debugpy",
  request = "launch",
  program = "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
  args    = function()
    local queue = vim.fn.input("Queue name to debug: ")
    return { "frappe", "worker", "--queue", queue }
  end,
  cwd     = "/workspace/frappe-bench/sites",
  justMyCode = false,
})

-- 3. Debug a specific frappe function
table.insert(dap.configurations.python, {
  name    = "Debug Specific Function",
  type    = "debugpy",
  request = "launch",
  program = "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
  args    = function()
    local fn_path = vim.fn.input("Frappe function path (e.g. myapp.module.fn): ")
    return { "frappe", "execute", fn_path }
  end,
  cwd     = "/workspace/frappe-bench/sites",
  justMyCode = false,
})

vim.notify("[fm] nvim-dap Frappe configurations loaded", vim.log.levels.INFO)
"""

PREBAKED_SITE_APPS = {
    "https://github.com/frappe/frappe": "version-15",
    "https://github.com/frappe/erpnext": "version-15",
    "https://github.com/frappe/hrms": "version-15",
}

NON_BASH_SUPPORTED_SERVICES = ["redis-cache", "redis-queue", "adminer", "mailpit"]
