"""Site Manager Module - Configuration and Constants"""

__all__ = [
    "VSCODE_LAUNCH_JSON",
    "VSCODE_TASKS_JSON",
    "VSCODE_SETTINGS_JSON",
    "NVIM_DAP_LUA",
    "PREBAKED_SITE_APPS",
    "NON_BASH_SUPPORTED_SERVICES",
]

VSCODE_LAUNCH_JSON = {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "fm-frappe-debug",
            "type": "debugpy",
            "request": "launch",
            "program": "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
            "preLaunchTask": "fm-kill-port",
            "args": ["frappe", "serve", "--port", "80", "--noreload", "--nothreading"],
            "cwd": "/workspace/frappe-bench/sites",
            "consoleName": "Frappe Debug",
            "env": {"DEV_SERVER": "1"},
            "justMyCode": False,
        },
        {
            "name": "Debug Specific Queue",
            "type": "debugpy",
            "request": "launch",
            "program": "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
            "args": [
                "frappe",
                "worker",
                "--queue",
                "${input:queue}",
            ],
            "consoleName": "${input:queue} worker",
            "cwd": "/workspace/frappe-bench/sites",
        },
        {
            "name": "Debug specific fuction",
            "type": "debugpy",
            "request": "launch",
            "program": "/workspace/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
            "cwd": "/workspace/frappe-bench/sites",
            "args": [
                "frappe",
                "execute",
                "${input:executable_path}",
            ],
            "consoleName": "Frappe Function",
        },
    ],
    "inputs": [
        {
            "id": "queue",
            "type": "command",
            "command": "extension.commandvariable.promptStringRemember",
            "args": {
                "key": "frappe_queue_name",
                "description": "Enter the queue name to debug.",
            },
        },
        {
            "id": "executable_path",
            "type": "command",
            "command": "extension.commandvariable.promptStringRemember",
            "args": {
                "key": "frappe_executable_path",
                "description": "Enter the path to frappe executable function",
            },
        },
    ],
}

VSCODE_TASKS_JSON = {
    "version": "2.0.0",
    "tasks": [
        {
            "label": "fm-kill-port",
            "type": "shell",
            "command": "/bin/bash",
            "args": ["-c", "fmx stop frappe && sleep 2"],
            "presentation": {"reveal": "never", "panel": "dedicated"},
            "options": {"ignoreExitCode": True},
            "problemMatcher": [],
        },
    ],
}

VSCODE_SETTINGS_JSON = {
    "python.defaultInterpreterPath": "/workspace/frappe-bench/env/bin/python",
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.formatOnSave": True,
        "editor.codeActionsOnSave": {"source.fixAll": True, "source.organizeImports": True},
        "editor.detectIndentation": True,
        "editor.tabSize": 4,
        "editor.insertSpaces": True,
    },
    "ruff.organizeImports": True,
    "ruff.fixAll": True,
    "ruff.lint.run": "onSave",
}

# Lua configuration for nvim-dap (Neovim Debug Adapter Protocol).
# Written as a .nvim.lua project-local file so nvim-dap picks it up
# automatically when the workspace is opened inside the container.
#
# Prerequisites (install in your Neovim config):
#   - mfussenegger/nvim-dap
#   - mfussenegger/nvim-dap-python  (optional but recommended)
# Add to config:
# vim.opt.exrc = true   -- load .nvim.lua from project root (Neovim ≥ 0.9: requires :trust)
#
# The three configurations mirror the VS Code launch.json exactly:
#   1. fm-frappe-debug      -- serves Frappe on port 80 with debugpy attached
#   2. Debug Specific Queue -- attach debugpy to a specific background worker
#   3. Debug Specific Function -- run a single frappe.execute() call under debugpy
#
# The pre-launch hook for fm-frappe-debug runs `fmx stop frappe && sleep 2`
# inside the container (equivalent to the VS Code fm-kill-port task) so the
# port is free before the debug server starts.
NVIM_DAP_LUA = """-- .nvim.lua  -  Frappe-Manager nvim-dap configuration
-- Generated by `fm nvim --debugger`. Do not edit manually.
-- Requires: mfussenegger/nvim-dap  (and optionally mfussenegger/nvim-dap-python)

local dap = require("dap")
local uv = vim.uv or vim.loop

dap.listeners.before.event_debugpySockets = dap.listeners.before.event_debugpySockets or {}
dap.listeners.before.event_debugpySockets["fm_debugpy_events"] = function()
end

dap.listeners.before.event_debugpyWaitingForServer = dap.listeners.before.event_debugpyWaitingForServer or {}
dap.listeners.before.event_debugpyWaitingForServer["fm_debugpy_events"] = function()
end

local function path_exists(path)
  return path and uv.fs_stat(path) ~= nil
end

local function parent_dir(path)
  return vim.fn.fnamemodify(path, ":h")
end

local function get_config_dir()
  local source = debug.getinfo(1, "S").source
  if type(source) == "string" and source:sub(1, 1) == "@" then
    return parent_dir(source:sub(2))
  end

  return vim.fn.getcwd()
end

local function find_bench_root(start_dir)
  local dir = start_dir
  while dir and dir ~= "/" do
    if path_exists(dir .. "/apps/frappe/frappe/utils/bench_helper.py") then
      return dir
    end

    local next_dir = parent_dir(dir)
    if next_dir == dir then
      break
    end
    dir = next_dir
  end

  return "/workspace/frappe-bench"
end

local BENCH_ROOT = find_bench_root(get_config_dir())
local BENCH_HELPER = BENCH_ROOT .. "/apps/frappe/frappe/utils/bench_helper.py"
local BENCH_SITES = BENCH_ROOT .. "/sites"
local REMOTE_BENCH_ROOT = "/workspace/frappe-bench"
local REMOTE_BENCH_HELPER = REMOTE_BENCH_ROOT .. "/apps/frappe/frappe/utils/bench_helper.py"
local REMOTE_BENCH_SITES = REMOTE_BENCH_ROOT .. "/sites"

local function infer_bench_path(bench_root)
  local dir = bench_root
  while dir and dir ~= "/" do
    if vim.fn.fnamemodify(dir, ":t") == "workspace" then
      return parent_dir(dir)
    end

    local next_dir = parent_dir(dir)
    if next_dir == dir then
      break
    end
    dir = next_dir
  end

  return ""
end

local BENCH_PATH = infer_bench_path(BENCH_ROOT)
local HOST_WORKSPACE_ROOT = BENCH_PATH ~= "" and (BENCH_PATH .. "/workspace") or BENCH_ROOT
local COMPOSE_FILE = BENCH_PATH ~= "" and (BENCH_PATH .. "/docker-compose.yml") or ""

local function can_use_docker_compose()
  return vim.fn.executable("docker") == 1 and COMPOSE_FILE ~= "" and path_exists(COMPOSE_FILE)
end

local function resolve_debugpy_python()
  local candidates = {
    BENCH_ROOT .. "/env/bin/python",
    "/workspace/frappe-bench/env/bin/python",
  }

  for _, candidate in ipairs(candidates) do
    if path_exists(candidate) then
      return candidate
    end
  end

  local python3 = vim.fn.exepath("python3")
  if python3 ~= "" then
    return python3
  end

  return "python"
end

local function resolve_config_value(value)
  if type(value) == "function" then
    return value()
  end

  return value
end

local function shell_join(args)
  local escaped = {}
  for _, arg in ipairs(args) do
    table.insert(escaped, vim.fn.shellescape(tostring(arg)))
  end

  return table.concat(escaped, " ")
end

local function run_system(command)
  local output = vim.fn.systemlist(command)
  return vim.v.shell_error, output
end

local function build_env_args(env)
  if type(env) ~= "table" then
    return {}
  end

  local parts = {}
  for key, value in pairs(env) do
    table.insert(parts, key .. "=" .. tostring(value))
  end

  return parts
end

local function get_frappe_container_id()
  local exit_code, output = run_system({ "docker", "compose", "-f", COMPOSE_FILE, "ps", "-q", "frappe" })
  if exit_code ~= 0 or not output[1] or output[1] == "" then
    vim.notify("[fm] could not resolve frappe container id", vim.log.levels.ERROR)
    return nil
  end

  return output[1]
end

local function get_frappe_container_ip(container_id)
  local exit_code, output = run_system({
    "docker",
    "inspect",
    "-f",
    "{{json .NetworkSettings.Networks}}",
    container_id,
  })

  if exit_code ~= 0 or not output[1] or output[1] == "" then
    vim.notify("[fm] could not resolve frappe container IP", vim.log.levels.ERROR)
    return nil
  end

  local ok, networks = pcall(vim.json.decode, output[1])
  if not ok or type(networks) ~= "table" then
    vim.notify("[fm] could not parse frappe container network data", vim.log.levels.ERROR)
    return nil
  end

  local preferred_keys = {
    "site-network",
    "global-backend-network",
    "global-frontend-network",
  }

  for _, preferred_key in ipairs(preferred_keys) do
    for network_name, network_data in pairs(networks) do
      if string.find(network_name, preferred_key, 1, true) then
        local ip = network_data and network_data.IPAddress
        if ip and ip ~= "" then
          return ip
        end
      end
    end
  end

  for _, network_data in pairs(networks) do
    local ip = network_data and network_data.IPAddress
    if ip and ip ~= "" then
      return ip
    end
  end

  vim.notify("[fm] no routable IP found for frappe container", vim.log.levels.ERROR)
  return nil
end

local function compose_exec_shell(shell_command)
  local command = { "docker", "compose", "-f", COMPOSE_FILE, "exec", "-T" }
  vim.list_extend(command, { "frappe", "/bin/bash", "-lc", shell_command })
  return command
end

local function compose_exec_command(args)
  local command = { "docker", "compose", "-f", COMPOSE_FILE, "exec", "-T", "frappe" }
  vim.list_extend(command, args)
  return command
end

local function cleanup_matching_debugpy_processes(config)
  local cleanup_matchers = resolve_config_value(config.fm_cleanup_matchers) or {}
  local debug_port = tostring(resolve_config_value(config.fm_cleanup_debug_port) or resolve_config_value(config.fm_port))
  local cleanup_script = [[
import os
import signal
import subprocess
import sys

current_pid = os.getpid()
debug_port = sys.argv[1]
matchers = sys.argv[2:]
output = subprocess.check_output(["ps", "-eo", "pid,args"], text=True)

for line in output.splitlines()[1:]:
    parts = line.strip().split(None, 1)
    if len(parts) < 2:
        continue

    pid = int(parts[0])
    command = parts[1]
    if pid == current_pid:
        continue

    is_debugpy_target = "-m debugpy" in command and all(matcher in command for matcher in matchers)
    is_debugpy_adapter = "debugpy/adapter" in command and f"--port {debug_port}" in command

    if is_debugpy_target or is_debugpy_adapter:
        try:
            os.kill(pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
]]

  local command = {
    REMOTE_BENCH_ROOT .. "/env/bin/python",
    "-c",
    cleanup_script,
    debug_port,
  }
  vim.list_extend(command, cleanup_matchers)

  local exit_code = run_system(compose_exec_command(command))
  if exit_code ~= 0 then
    vim.notify("[fm] failed to clean stale debugpy processes before launch", vim.log.levels.WARN)
  end
end

local function wait_for_debugpy_adapter(debug_port, log_file)
  local wait_script = [[
import subprocess
import sys

debug_port = sys.argv[1]
output = subprocess.check_output(["ps", "-eo", "pid,args"], text=True)

for line in output.splitlines()[1:]:
    parts = line.strip().split(None, 1)
    if len(parts) < 2:
        continue

    command = parts[1]
    if "debugpy/adapter" in command and f"--port {debug_port}" in command:
        raise SystemExit(0)

raise SystemExit(1)
]]

  local command = {
    REMOTE_BENCH_ROOT .. "/env/bin/python",
    "-c",
    wait_script,
    tostring(debug_port),
  }

  local ready = vim.wait(7000, function()
    local exit_code = run_system(compose_exec_command(command))
    return exit_code == 0
  end, 120)

  if ready then
    return true
  end

  local _, log_output = run_system(
    compose_exec_shell(
      "if [ -f "
        .. vim.fn.shellescape(log_file)
        .. " ]; then tail -n 8 "
        .. vim.fn.shellescape(log_file)
        .. "; else echo __FM_DEBUGPY_LOG_MISSING__; fi"
    )
  )

  local details = ""
  if log_output and log_output[1] and log_output[1] ~= "__FM_DEBUGPY_LOG_MISSING__" then
    details = " (last log: " .. log_output[1] .. ")"
  end

  vim.notify(
    "[fm] timed out waiting for debugpy adapter on port " .. tostring(debug_port) .. details,
    vim.log.levels.ERROR
  )
  return false
end

local function start_container_debug_session(config)
  local port = resolve_config_value(config.fm_port)
  local bench_args = resolve_config_value(config.fm_args) or {}
  local remote_program = resolve_config_value(config.fm_remote_program) or REMOTE_BENCH_HELPER
  local env_args = build_env_args(resolve_config_value(config.fm_env))
  local prelaunch = resolve_config_value(config.fm_prelaunch)
  local log_file = "/tmp/fm-debugpy-" .. tostring(port) .. ".log"

  cleanup_matching_debugpy_processes(config)

  local launch_args = {
    REMOTE_BENCH_ROOT .. "/env/bin/python",
    "-m",
    "debugpy",
    "--listen",
    "0.0.0.0:" .. tostring(port),
    "--wait-for-client",
    remote_program,
  }

  vim.list_extend(launch_args, bench_args)
  if #env_args > 0 then
    local with_env = { "env" }
    vim.list_extend(with_env, env_args)
    vim.list_extend(with_env, launch_args)
    launch_args = with_env
  end

  local shell_parts = {
    "cd " .. vim.fn.shellescape(REMOTE_BENCH_SITES),
    "nohup " .. shell_join(launch_args) .. " >" .. log_file .. " 2>&1 < /dev/null &",
  }

  if prelaunch and prelaunch ~= "" then
    table.insert(shell_parts, 1, prelaunch)
  end

  local exit_code, output = run_system(compose_exec_shell(table.concat(shell_parts, "; ")))
  if exit_code ~= 0 then
    local details = ""
    if output and output[1] then
      details = ": " .. output[1]
    end
    vim.notify("[fm] could not start debugpy inside frappe container" .. details, vim.log.levels.ERROR)
    return nil, nil
  end

  local container_id = get_frappe_container_id()
  if not container_id then
    return nil, nil
  end

  local host = get_frappe_container_ip(container_id)
  if not host then
    return nil, nil
  end

  if not wait_for_debugpy_adapter(port, log_file) then
    return nil, nil
  end

  return host, port
end

-- ---------------------------------------------------------------------------
-- Adapter: debugpy
-- ---------------------------------------------------------------------------
dap.adapters.fm_python = function(callback, config)
  if config.request == "attach" and can_use_docker_compose() then
    local host, port = start_container_debug_session(config)
    if host and port then
      callback({
        type = "server",
        host = host,
        port = port,
        options = {
          source_filetype = "python",
        },
      })
    else
      vim.notify("[fm] attach bootstrap failed; falling back to local debugpy adapter", vim.log.levels.WARN)
      callback({
        type = "executable",
        command = resolve_debugpy_python(),
        args = { "-m", "debugpy.adapter" },
      })
    end
    return
  end

  callback({
    type = "executable",
    command = resolve_debugpy_python(),
    args = { "-m", "debugpy.adapter" },
  })
end

-- ---------------------------------------------------------------------------
-- Configurations
-- ---------------------------------------------------------------------------
dap.configurations.python = dap.configurations.python or {}

local function run_python_config(index)
  local config = dap.configurations.python[index]
  if not config then
    vim.notify("[fm] python debug configuration #" .. tostring(index) .. " not available", vim.log.levels.ERROR)
    return
  end

  dap.run(config)
end

local function replace_user_command(name, callback, opts)
  pcall(vim.api.nvim_del_user_command, name)
  vim.api.nvim_create_user_command(name, callback, opts)
end

local function toggle_debug_ui()
  local ok, dapui = pcall(require, "dapui")
  if not ok then
    vim.notify("[fm] nvim-dap-ui is not installed", vim.log.levels.WARN)
    return
  end

  dapui.toggle({})
end

local function setup_dapui_listeners()
  local ok, dapui = pcall(require, "dapui")
  if not ok then
    return
  end

  dap.listeners.after.event_initialized["fm_dapui"] = function()
    dapui.open()
  end

  dap.listeners.before.event_terminated["fm_dapui"] = function()
    dapui.close()
  end

  dap.listeners.before.event_exited["fm_dapui"] = function()
    dapui.close()
  end
end

setup_dapui_listeners()

-- 1. Frappe dev-server debug session
table.insert(dap.configurations.python, {
  name    = "fm-frappe-debug",
  type    = "fm_python",
  request = can_use_docker_compose() and "attach" or "launch",
  program = BENCH_HELPER,
  args    = { "frappe", "serve", "--port", "80", "--noreload", "--nothreading" },
  cwd     = BENCH_SITES,
  env     = { DEV_SERVER = "1" },
  fm_env  = { DEV_SERVER = "1" },
  fm_args = { "frappe", "serve", "--port", "80", "--noreload", "--nothreading" },
  fm_port = 5678,
  fm_cleanup_debug_port = 5678,
  fm_cleanup_matchers = { "frappe serve", "--port", "80" },
  fm_prelaunch = "fmx stop frappe >/dev/null 2>&1 || true; sleep 2",
  justMyCode = false,
  pathMappings = {
    {
      localRoot = HOST_WORKSPACE_ROOT,
      remoteRoot = "/workspace",
    },
  },
})

-- 2. Debug a specific background worker queue
table.insert(dap.configurations.python, {
  name    = "Debug Specific Queue",
  type    = "fm_python",
  request = can_use_docker_compose() and "attach" or "launch",
  program = BENCH_HELPER,
  args    = function()
    local queue = vim.fn.input("Queue name to debug: ")
    return { "frappe", "worker", "--queue", queue }
  end,
  cwd     = BENCH_SITES,
  fm_args = function()
    local queue = vim.fn.input("Queue name to debug: ")
    return { "frappe", "worker", "--queue", queue }
  end,
  fm_port = 5679,
  fm_cleanup_debug_port = 5679,
  fm_cleanup_matchers = { "frappe worker" },
  justMyCode = false,
  pathMappings = {
    {
      localRoot = HOST_WORKSPACE_ROOT,
      remoteRoot = "/workspace",
    },
  },
})

-- 3. Debug a specific frappe function
table.insert(dap.configurations.python, {
  name    = "Debug Specific Function",
  type    = "fm_python",
  request = can_use_docker_compose() and "attach" or "launch",
  program = BENCH_HELPER,
  args    = function()
    local fn_path = vim.fn.input("Frappe function path (e.g. myapp.module.fn): ")
    return { "frappe", "execute", fn_path }
  end,
  cwd     = BENCH_SITES,
  fm_args = function()
    local fn_path = vim.fn.input("Frappe function path (e.g. myapp.module.fn): ")
    return { "frappe", "execute", fn_path }
  end,
  fm_port = 5680,
  fm_cleanup_debug_port = 5680,
  fm_cleanup_matchers = { "frappe execute" },
  justMyCode = false,
  pathMappings = {
    {
      localRoot = HOST_WORKSPACE_ROOT,
      remoteRoot = "/workspace",
    },
  },
})

replace_user_command("FmDebugStart", function()
  run_python_config(1)
end, { desc = "Start Frappe web debugger" })

replace_user_command("FmDebugQueue", function()
  run_python_config(2)
end, { desc = "Start Frappe queue debugger" })

replace_user_command("FmDebugFunction", function()
  run_python_config(3)
end, { desc = "Start Frappe function debugger" })

replace_user_command("FmDebugToggleUI", function()
  toggle_debug_ui()
end, { desc = "Toggle DAP UI" })

vim.keymap.set("n", "<leader>ds", function()
  run_python_config(1)
end, { desc = "Start FM web debug session" })

vim.keymap.set("n", "<leader>du", function()
  toggle_debug_ui()
end, { desc = "Toggle FM debug UI" })

vim.notify("[fm] nvim-dap Frappe configurations loaded", vim.log.levels.INFO)
"""

PREBAKED_SITE_APPS = {
    "https://github.com/frappe/frappe": "version-15",
    "https://github.com/frappe/erpnext": "version-15",
    "https://github.com/frappe/hrms": "version-15",
}

NON_BASH_SUPPORTED_SERVICES = ["redis-cache", "redis-queue", "adminer", "mailpit"]
