#!/usr/bin/bash
cleanup() {
    echo "Received signal, performing cleanup..."
    if [ -n "$nginx_pid" ]; then
        nginx -s quit
        wait "$nginx_pid"
    fi
    exit 0
}

trap cleanup SIGQUIT SIGTERM

# Check if configuration already exists (generated by frappe-manager)
if [[ -f "/etc/nginx/conf.d/default.conf" ]]; then
    echo "Using nginx configuration generated by frappe-manager"
    
    # Test nginx configuration
    if ! nginx -t; then
        echo "Nginx configuration test failed!"
        exit 1
    fi
else
    echo "Warning: No nginx configuration found at /etc/nginx/conf.d/default.conf"
    echo "This might be expected for new benches. Nginx will use default configuration."
    
    # Create a minimal default config if none exists
    cat > /etc/nginx/conf.d/default.conf << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    location / {
        return 503 "Bench configuration not yet generated by frappe-manager";
    }
}
EOF
fi

echo "Starting nginx..."
nginx -g 'daemon off;' &

nginx_pid=$!
wait $nginx_pid
