"""v1.0.0 services migration: converting shared `vhostd/<domain>` marked blocks into
`ProxyDropins` fragments.

Before this, maintenance/https-redirect/hsts each owned a `# fm:<name> BEGIN/END` region inside
the single, shared `vhostd/<domain>` file, and upload-limit had no marker at all. An existing
host's `vhostd/` directory is the only record of an operator's settings, so this migration must
read every one of those forms out of it, write the equivalent fragment, and leave the file holding
only the `# fm:include` bootstrap plus whatever foreign content was already there -- without ever
reloading nginx while both a marker and its fragment could be live at once.

No test touches docker or the network: every services tree lives in `tmp_path`, and the proxy
reload is swapped for a `Mock()` at the migration's own `_reload_proxy` boundary.
"""

from pathlib import Path
from unittest.mock import MagicMock, Mock

import pytest
import yaml

from frappe_manager.migration_manager.migrations.migrate_1_0_0 import (
    _LEGACY_HTTPS_REDIRECT_CONFIG,
    MigrationV100,
)
from frappe_manager.site_manager.modules.upload_limit import upload_limit_conf
from frappe_manager.ssl_manager.proxy_conf import hsts_conf, https_redirect_conf

MAINTENANCE_BODY = (
    'set $fm_maintenance 1;\n'
    'set $fm_maintenance_bypass_token "tok-xyz";\n'
    'if ($arg_fm_bypass = "tok-xyz") { set $fm_maintenance 0; }\n'
)
MAINTENANCE_BLOCK = (
    "# fm:maintenance BEGIN (bench: my-bench) generated by `fm maintenance`; do not edit this block\n"
    + MAINTENANCE_BODY
    + "# fm:maintenance END\n"
)

HTTPS_REDIRECT_BLOCK = (
    "# fm:https-redirect BEGIN\nset $redirect_to_https 0;\nif ($scheme = http) { set $redirect_to_https 1; }\n"
    "# fm:https-redirect END\n"
)

HSTS_VALUE = "max-age=63072000; includeSubDomains; preload"
HSTS_BLOCK = (
    "# fm:hsts BEGIN\n"
    'set $fm_hsts_value "";\n'
    "if ($fm_client_scheme = https) {\n"
    f'    set $fm_hsts_value "{HSTS_VALUE}";\n'
    "}\n"
    "add_header Strict-Transport-Security $fm_hsts_value always;\n"
    "# fm:hsts END\n"
)


def _bootstrap(domain: str) -> str:
    return f"# fm:include BEGIN\ninclude /etc/nginx/fm.d/vhost/{domain}/*.conf;\n# fm:include END\n"


def _setup(tmp_path: Path, monkeypatch) -> Path:
    services_dir = tmp_path / "services"
    (services_dir / "nginx-proxy" / "vhostd").mkdir(parents=True)
    monkeypatch.setattr("frappe_manager.CLI_SERVICES_DIRECTORY", services_dir)
    return services_dir


def _migration() -> MigrationV100:
    m = MigrationV100(output_handler=MagicMock())
    m.backup_manager = MagicMock()
    m.services_manager = MagicMock()
    return m


def _vhostd(services_dir: Path) -> Path:
    return services_dir / "nginx-proxy" / "vhostd"


def _fmd_vhost(services_dir: Path) -> Path:
    return services_dir / "nginx-proxy" / "fmd" / "vhost"


def test_all_three_marked_blocks_become_fragments_and_a_bootstrap_only_vhost_file(tmp_path, monkeypatch):
    """The maintenance fragment carries the ORIGINAL block body verbatim -- the bypass token and
    allow-lists already live in it and must not be re-minted by a migration."""
    services_dir = _setup(tmp_path, monkeypatch)
    domain = "a.test"
    (_vhostd(services_dir) / domain).write_text(MAINTENANCE_BLOCK + HTTPS_REDIRECT_BLOCK + HSTS_BLOCK)

    migration = _migration()
    migration._convert_proxy_vhostd_to_fragments()

    fmd = _fmd_vhost(services_dir) / domain
    assert (fmd / "20-maintenance.conf").read_text() == MAINTENANCE_BODY
    assert (fmd / "40-https-redirect.conf").read_text() == https_redirect_conf()
    assert (fmd / "30-hsts.conf").read_text() == hsts_conf(HSTS_VALUE)
    assert (_vhostd(services_dir) / domain).read_text() == _bootstrap(domain)


def test_pre_marker_legacy_https_redirect_text_is_converted_too(tmp_path, monkeypatch):
    """Real benches deployed before marker blocks existed hold the exact unmarked legacy text;
    it must be recognised and converted just like a marked `# fm:https-redirect` block."""
    services_dir = _setup(tmp_path, monkeypatch)
    domain = "legacy.test"
    (_vhostd(services_dir) / domain).write_text(_LEGACY_HTTPS_REDIRECT_CONFIG)

    migration = _migration()
    migration._convert_proxy_vhostd_to_fragments()

    fragment = _fmd_vhost(services_dir) / domain / "40-https-redirect.conf"
    assert fragment.read_text() == https_redirect_conf()
    assert (_vhostd(services_dir) / domain).read_text() == _bootstrap(domain)


def test_unmarked_client_max_body_size_is_adopted_as_the_upload_limit_fragment(tmp_path, monkeypatch):
    """The one unmarked directive that predates fm's marker scheme entirely: this is the one
    place the ambiguity (is this fm's or an operator's?) is resolvable, so it is adopted and
    removed from the shared vhost.d file."""
    services_dir = _setup(tmp_path, monkeypatch)
    domain = "upload.test"
    (_vhostd(services_dir) / domain).write_text("client_max_body_size 75m;\n")

    migration = _migration()
    migration._convert_proxy_vhostd_to_fragments()

    fragment = _fmd_vhost(services_dir) / domain / "10-upload-limit.conf"
    assert fragment.read_text() == upload_limit_conf("75m")
    assert (_vhostd(services_dir) / domain).read_text() == _bootstrap(domain)


def test_a_domain_with_only_foreign_content_is_left_completely_untouched(tmp_path, monkeypatch):
    """No fm marker, no legacy text, no unmarked upload-limit directive: nothing here belongs to
    fm, so neither a fragment nor the include bootstrap may be written."""
    services_dir = _setup(tmp_path, monkeypatch)
    domain = "foreign.test"
    original = "# hand-written by operator\nadd_header X-Op yes;\n"
    (_vhostd(services_dir) / domain).write_text(original)

    migration = _migration()
    migration._convert_proxy_vhostd_to_fragments()

    assert (_vhostd(services_dir) / domain).read_text() == original
    assert not (_fmd_vhost(services_dir) / domain).exists()
    migration.backup_manager.backup.assert_not_called()


def test_foreign_content_alongside_fm_blocks_survives_the_rewrite_byte_for_byte(tmp_path, monkeypatch):
    services_dir = _setup(tmp_path, monkeypatch)
    domain = "mixed.test"
    foreign_before = "# before\nadd_header X-Before yes;\n"
    foreign_after = "# after\nadd_header X-After yes;\n"
    (_vhostd(services_dir) / domain).write_text(foreign_before + MAINTENANCE_BLOCK + foreign_after)

    migration = _migration()
    migration._convert_proxy_vhostd_to_fragments()

    assert (_vhostd(services_dir) / domain).read_text() == _bootstrap(domain) + foreign_before + foreign_after


def test_running_the_conversion_twice_changes_nothing_the_second_time(tmp_path, monkeypatch):
    services_dir = _setup(tmp_path, monkeypatch)
    domain = "idem.test"
    (_vhostd(services_dir) / domain).write_text(MAINTENANCE_BLOCK)

    migration = _migration()
    migration._reload_proxy = Mock()
    migration._convert_proxy_vhostd_to_fragments()

    vhost_after_first = (_vhostd(services_dir) / domain).read_text()
    fragment_after_first = (_fmd_vhost(services_dir) / domain / "20-maintenance.conf").read_text()
    assert migration._reload_proxy.call_count == 1

    migration._convert_proxy_vhostd_to_fragments()

    assert (_vhostd(services_dir) / domain).read_text() == vhost_after_first
    assert (_fmd_vhost(services_dir) / domain / "20-maintenance.conf").read_text() == fragment_after_first
    assert migration._reload_proxy.call_count == 1, "nothing changed, so the second pass must not reload"


@pytest.mark.parametrize("service_name", ["nginx-proxy", "global-nginx-proxy"])
def test_compose_gains_the_fmd_mount_under_either_service_name(tmp_path, monkeypatch, service_name):
    """This runs before `_service_rename_services`, so a legacy install's proxy service is still
    named `global-nginx-proxy`; either name must grow the mount `ProxyDropins` fragments need."""
    services_dir = _setup(tmp_path, monkeypatch)
    compose_path = services_dir / "docker-compose.yml"
    doc = {"services": {service_name: {"image": "x", "volumes": ["./nginx-proxy/vhostd:/etc/nginx/vhost.d"]}}}
    compose_path.write_text(yaml.safe_dump(doc, sort_keys=False))

    migration = _migration()
    migration._convert_proxy_vhostd_to_fragments()

    written = yaml.safe_load(compose_path.read_text())
    assert "./nginx-proxy/fmd:/etc/nginx/fm.d" in written["services"][service_name]["volumes"]


def test_proxy_is_reloaded_exactly_once_for_the_whole_step(tmp_path, monkeypatch):
    """Reloading per domain -- instead of once after every domain is converted -- risks a moment
    where a marked block and its fragment are both live, which duplicates a `location` and takes
    down nginx for every bench on the host."""
    services_dir = _setup(tmp_path, monkeypatch)
    (_vhostd(services_dir) / "one.test").write_text("client_max_body_size 10m;\n")
    (_vhostd(services_dir) / "two.test").write_text(MAINTENANCE_BLOCK)
    (_vhostd(services_dir) / "three.test").write_text(HTTPS_REDIRECT_BLOCK)

    migration = _migration()
    migration._reload_proxy = Mock()
    migration._convert_proxy_vhostd_to_fragments()

    migration._reload_proxy.assert_called_once()
