benchname := "fmd.localhost"

default:
    @just --list

run *args:
    fm shell {{benchname}} -c '.venv/bin/fmx {{args}}'

sync:
    rsync -avz . ~/frappe/sites/{{benchname}}/workspace/frappe-bench/fmx/
    fm shell {{benchname}} -c "cd /workspace/frappe-bench && uv pip install -U -e fmx"

shell:
    just sync
    fm shell {{benchname}}
