[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fmx"
version = "1.2.0"
authors = [
  { name="fmx - fm container helper cli", email="sys@rtcamp.com" },
]
description = "A CLI tool to interact with supervisord instances managed by Frappe-Manager."
license = { text = "MIT" }
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]

dependencies = [
    "typer>=0.26.0",
    "rich>=15.0.0,<16.0.0",
    "supervisor>=4.3.0,<5.0.0",
    "redis>=8.0.0",
    "rq>=2.12.0",
    "typer-examples",
]

[project.urls]
"Homepage" = "https://github.com/rtCamp/Frappe-Manager"
"Repository" = "https://github.com/rtCamp/Frappe-Manager"
"Bug Tracker" = "https://github.com/rtCamp/Frappe-Manager/issues"

[project.scripts]
fmx = "fmx.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["fmx"]

[tool.uv]
package = true

[tool.uv.sources]
typer-examples = { git = "https://github.com/Xieyt/typer-examples", tag = "v1.0.0" }

[dependency-groups]
dev = [
    "nuitka>=4.1.0",
]
