name: Publish image

permissions:
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use Docker build cache'
        required: false
        type: boolean
        default: true
  push:
    tags:
      - v*

jobs:
  build-and-push:
    name: Build and push image
    strategy:
      matrix:
        os: [self-hosted-arm64,ubuntu-latest]
        platform: [linux/amd64, linux/arm64]
        service_name: [frappe, nginx]
        exclude:
          - os: ubuntu-latest
            platform: linux/arm64
          - os: self-hosted-arm64
            platform: linux/amd64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set USE_CACHE variable
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.use_cache }}" == "true" ]]; then
              echo "USE_CACHE=true" >> $GITHUB_ENV
            else
              echo "USE_CACHE=false" >> $GITHUB_ENV
            fi
          else
            echo "USE_CACHE=true" >> $GITHUB_ENV
          fi

      - name: Checkout latest tag when job is schedule or push
        if: github.event_name == 'schedule' || github.event_name == 'push'
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            git fetch --all
            git checkout main
            latest_tag=$(git describe --abbrev=0 --tags)
          elif [[ "${{ github.ref == 'refs/tags/v*' }}" == 'true' ]]; then
            latest_tag=${GITHUB_REF/refs\/tags\//}
          else
            latest_tag=$(git describe --abbrev=0 --tags)
          fi

          echo "Checkout $latest_tag"
          git checkout "$latest_tag"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image names
        run: |
          owner=$( echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]' )
          # Read version from __about__.py
          version=$(grep '^__version__' frappe_manager/__about__.py | sed 's/__version__ = "\(.*\)"/\1/')
          tag="v${version}"
          echo "Image tag $tag"
          echo "image_name=ghcr.io/${owner}/frappe-manager-${{ matrix.service_name }}:$(basename ${{ matrix.platform }})-${tag}" >> $GITHUB_ENV

      - name: Set owner
        run: |
          echo "owned=$( echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]' )" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Docker/${{ matrix.service_name }}/.
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ env.image_name }}
          provenance: false
          cache-from: ${{ env.USE_CACHE == 'true' && format('type=registry,ref=ghcr.io/{0}/frappe-manager-{1}:buildcache-{2}', env.owned, matrix.service_name, matrix.platform == 'linux/amd64' && 'amd64' || 'arm64') || '' }}
          cache-to: ${{ format('type=registry,ref=ghcr.io/{0}/frappe-manager-{1}:buildcache-{2},mode=max', env.owned, matrix.service_name, matrix.platform == 'linux/amd64' && 'amd64' || 'arm64') || '' }}

      - name: Prune buildx cache (self-hosted only)
        if: startsWith(matrix.os, 'self-hosted')
        run: |
          docker buildx prune -af

  combine:
    name: Combine both platform images
    needs: build-and-push
    strategy:
      matrix:
        os: [ubuntu-latest]
        service_name: [frappe, nginx]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout latest tag when job is schedule or push
        if: github.event_name == 'schedule' || github.event_name == 'push'
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            git fetch --all
            git checkout main
            latest_tag=$(git describe --abbrev=0 --tags)
          elif [[ "${{ github.ref == 'refs/tags/v*' }}" == 'true' ]]; then
            latest_tag=${GITHUB_REF/refs\/tags\//}
          else
            latest_tag=$(git describe --abbrev=0 --tags)
          fi

          echo "Checkout $latest_tag"
          git checkout "$latest_tag"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Combine manifest and push
        run: |
          # Read version from __about__.py
          version=$(grep '^__version__' frappe_manager/__about__.py | sed 's/__version__ = "\(.*\)"/\1/')
          tag="v${version}"
          owner=$( echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]' )
          
          img="ghcr.io/${owner}/frappe-manager-${{ matrix.service_name }}"
          rm -rf ~/.docker/manifests
          docker pull "$img:amd64-${tag}"
          docker pull "$img:arm64-${tag}"
          docker manifest create "$img":"${tag}" \
            --amend "$img":amd64-${tag} \
            --amend "$img":arm64-${tag}
          docker manifest push "$img:${tag}"

      - name: Cleanup
        run: |
          rm -rf ~/.docker/manifests
