name: E2E migration testing

on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  e2e-migration-from-0_9_0-to-latest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-ver: ["3.11", "3.12"]
        os: [ubuntu-latest]
        # os: [self-hosted-arm64, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: header
        run: |
          echo -e "\e[1;33m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\e[0m
          \e[1;33m┃\e[0m \e[1;36m Migration from v0.9.0 to latest \e[0m \e[1;33m┃\e[0m
          \e[1;33m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\e[0m"

      - name: install frappe from v0.9.0
        run: |
          cd /tmp
          python -m pip install -U git+https://github.com/rtCamp/Frappe-Manager.git@v0.9.0

      - name: frappe version
        run: fm --version

      - name: e2e run
        timeout-minutes: 20
        working-directory: test
        run: |
          ./migration_test.sh oldToNew

      - name: cleanup
        if: always()
        run: |
          python -m pip uninstall -y frappe-manager
          sudo rm -rf ~/frappe

  e2e-migration-from-before_latest-to-latest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-ver: ["3.11", "3.12"]
        os: [ubuntu-latest]
        # os: [self-hosted-arm64, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: install jq
        run: |
          sudo apt upgrade -y
          sudo apt install -y jq curl
      - name: header
        run: |
          echo -e "\e[1;33m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\e[0m
          \e[1;33m┃\e[0m \e[1;36m Migration from latest~1 to latest \e[0m \e[1;33m┃\e[0m
          \e[1;33m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\e[0m"

      - name: install frappe previous the latest release
        run: |
          python -m pip install -U git+https://github.com/rtCamp/Frappe-Manager.git@$(curl --silent https://api.github.com/repos/rtCamp/Frappe-Manager/tags | jq -r '.[1].name')

      - name: frappe version
        run: fm --version

      - name: e2e run
        timeout-minutes: 30
        working-directory: test
        run: |
          ./migration_test.sh semiNewToNew

      - name: cleanup
        if: always()
        run: |
          python -m pip uninstall -y frappe-manager
          sudo rm -rf ~/frappe
