name: Publish to PyPI

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
